# =========================================================================
#  Figure 5.2: MCMC Convergence Diagnostics
# =========================================================================
#  6-panel figure: trace plots, ACF, and Geweke diagnostic
#  for well-tuned vs. poorly-tuned Random Walk MH.
#
#  Author: Alessia Paccagnini
#  Textbook: Macroeconometrics
#
#  NOTE: Requires mcmc_chain_good.csv and mcmc_chain_bad.csv
#        generated by mcmc_generate_chains.py.
# =========================================================================

rm(list = ls())

# -----------------------------------------------------------------
# Load pre-generated chains
# -----------------------------------------------------------------
chain_good <- as.matrix(read.csv("mcmc_chain_good.csv"))
chain_bad  <- as.matrix(read.csv("mcmc_chain_bad.csv"))
n_iter <- nrow(chain_good)

# Acceptance rate from chain (count rows where values changed)
ar_good <- mean(apply(diff(chain_good), 1, function(r) any(r != 0)))
ar_bad  <- mean(apply(diff(chain_bad), 1, function(r) any(r != 0)))

cat(sprintf("Well-tuned:   acceptance rate = %.1f%%\n", 100 * ar_good))
cat(sprintf("Poorly tuned: acceptance rate = %.1f%%\n", 100 * ar_bad))

# -----------------------------------------------------------------
# ACF and ESS
# -----------------------------------------------------------------
compute_acf <- function(x, max_lag = 100) {
  n   <- length(x)
  x_c <- x - mean(x)
  v   <- var(x_c) * (n - 1) / n  # population variance
  acf_vals <- numeric(max_lag + 1)
  for (k in 0:max_lag) {
    acf_vals[k + 1] <- mean(x_c[1:(n - k)] * x_c[(k + 1):n]) / v
  }
  acf_vals
}

compute_ess <- function(acf_vals, n) {
  tau <- 1.0
  for (k in 2:length(acf_vals)) {
    if (acf_vals[k] < 0) break
    tau <- tau + 2 * acf_vals[k]
  }
  n / tau
}

max_lag  <- 100
acf_good <- compute_acf(chain_good[, 1], max_lag)
acf_bad  <- compute_acf(chain_bad[, 1], max_lag)
ess_good <- compute_ess(acf_good, n_iter)
ess_bad  <- compute_ess(acf_bad, n_iter)

cat(sprintf("Well-tuned:   ESS = %.0f\n", ess_good))
cat(sprintf("Poorly tuned: ESS = %.0f\n", ess_bad))

# -----------------------------------------------------------------
# Geweke diagnostic
# -----------------------------------------------------------------
spectral_var <- function(x, max_bw = NULL) {
  n_x <- length(x)
  if (is.null(max_bw)) max_bw <- floor(sqrt(n_x))
  x_c <- x - mean(x)
  gamma_0 <- var(x_c) * (n_x - 1) / n_x
  s <- gamma_0
  for (k in 1:max_bw) {
    w <- 1 - k / (max_bw + 1)
    gamma_k <- mean(x_c[1:(n_x - k)] * x_c[(k + 1):n_x])
    s <- s + 2 * w * gamma_k
  }
  s / n_x
}

geweke_rolling <- function(chain_1d, first_frac = 0.1, window_starts = NULL) {
  n   <- length(chain_1d)
  n_a <- floor(first_frac * n)
  chain_a <- chain_1d[1:n_a]
  mean_a  <- mean(chain_a)
  var_a   <- spectral_var(chain_a)

  if (is.null(window_starts)) {
    n_b     <- floor(0.5 * n)
    chain_b <- chain_1d[(n - n_b + 1):n]
    mean_b  <- mean(chain_b)
    var_b   <- spectral_var(chain_b)
    denom   <- sqrt(var_a + var_b)
    z       <- ifelse(denom > 0, (mean_a - mean_b) / denom, 0)
    return(z)
  } else {
    z_scores <- numeric(length(window_starts))
    for (i in seq_along(window_starts)) {
      chain_b <- chain_1d[window_starts[i]:n]
      mean_b  <- mean(chain_b)
      var_b   <- spectral_var(chain_b)
      denom   <- sqrt(var_a + var_b)
      z_scores[i] <- ifelse(denom > 0, (mean_a - mean_b) / denom, 0)
    }
    return(z_scores)
  }
}

window_starts <- seq(floor(0.2 * n_iter), floor(0.8 * n_iter), by = 50)
geweke_good   <- geweke_rolling(chain_good[, 1], 0.1, window_starts)
geweke_bad    <- geweke_rolling(chain_bad[, 1], 0.1, window_starts)

z_good <- geweke_rolling(chain_good[, 1], 0.1)
z_bad  <- geweke_rolling(chain_bad[, 1], 0.1)

cat(sprintf("\nGeweke Z (first 10%% vs last 50%%):\n"))
cat(sprintf("  Well-tuned:   Z = %.3f (p = %.3f)\n", z_good, 2 * (1 - pnorm(abs(z_good)))))
cat(sprintf("  Poorly tuned: Z = %.3f (p = %.3f)\n", z_bad, 2 * (1 - pnorm(abs(z_bad)))))

# -----------------------------------------------------------------
# Figure: 3 rows x 2 columns
# -----------------------------------------------------------------
c_good <- "#2171B5"
c_bad  <- "#CB181D"

# --- Save directly to PNG (works everywhere) ---
png("figure_mcmc_convergence.png", width = 1400, height = 1300, res = 150)
par(mfrow = c(3, 2), mar = c(4.5, 4.5, 3.5, 1), oma = c(0, 0, 4, 0))

# Row 1: Trace plots
plot(chain_good[, 1], type = "l", col = adjustcolor(c_good, alpha = 0.8), lwd = 0.3,
     xlab = "Iteration", ylab = expression(theta[1]),
     main = sprintf("(a) Well-Tuned Trace Plot (c = 1.70)\nAcceptance rate: %.1f%%, ESS: %.0f",
                    100 * ar_good, ess_good),
     font.main = 2, ylim = c(-4, 4), xlim = c(1, n_iter))
abline(h = 0, lty = 2, lwd = 1, col = "black")

plot(chain_bad[, 1], type = "l", col = adjustcolor(c_bad, alpha = 0.8), lwd = 0.3,
     xlab = "Iteration", ylab = expression(theta[1]),
     main = sprintf("(b) Poorly-Tuned Trace Plot (c = 0.05)\nAcceptance rate: %.1f%%, ESS: %.0f",
                    100 * ar_bad, ess_bad),
     font.main = 2, ylim = c(-4, 4), xlim = c(1, n_iter))
abline(h = 0, lty = 2, lwd = 1, col = "black")

# Row 2: ACF
barplot(acf_good, col = adjustcolor(c_good, alpha = 0.7), border = NA,
        space = 0, names.arg = NA, ylim = c(-0.1, 1.05),
        xlab = "Lag", ylab = "ACF",
        main = "(c) Well-Tuned Autocorrelation Function", font.main = 2)
abline(h = 0, lwd = 0.8)
abline(h = c(-1, 1) * 1.96 / sqrt(n_iter), lty = 2, col = "gray50")

barplot(acf_bad, col = adjustcolor(c_bad, alpha = 0.7), border = NA,
        space = 0, names.arg = NA, ylim = c(-0.1, 1.05),
        xlab = "Lag", ylab = "ACF",
        main = "(d) Poorly-Tuned Autocorrelation Function", font.main = 2)
abline(h = 0, lwd = 0.8)
abline(h = c(-1, 1) * 1.96 / sqrt(n_iter), lty = 2, col = "gray50")

# Row 3: Geweke diagnostic
plot(window_starts, geweke_good, type = "l", col = c_good, lwd = 1.5,
     xlab = "Start of comparison window", ylab = "Geweke Z-score",
     main = sprintf("(e) Well-Tuned Geweke Diagnostic (Z = %.2f)", z_good),
     font.main = 2, ylim = c(-4, 4))
rect(window_starts[1], -1.96, tail(window_starts, 1), 1.96,
     col = adjustcolor("gray", alpha = 0.08), border = NA)
abline(h = 0, lwd = 0.8)
abline(h = c(-1.96, 1.96), lty = 2, col = "gray50")
text(tail(window_starts, 1) - 200, 2.3, "95% critical values",
     cex = 0.7, col = "gray40", pos = 2, font = 3)

plot(window_starts, geweke_bad, type = "l", col = c_bad, lwd = 1.5,
     xlab = "Start of comparison window", ylab = "Geweke Z-score",
     main = sprintf("(f) Poorly-Tuned Geweke Diagnostic (Z = %.2f)", z_bad),
     font.main = 2, ylim = c(-4, 4))
rect(window_starts[1], -1.96, tail(window_starts, 1), 1.96,
     col = adjustcolor("gray", alpha = 0.08), border = NA)
abline(h = 0, lwd = 0.8)
abline(h = c(-1.96, 1.96), lty = 2, col = "gray50")
text(tail(window_starts, 1) - 200, 2.3, "95% critical values",
     cex = 0.7, col = "gray40", pos = 2, font = 3)

mtext("MCMC Convergence Diagnostics: Random Walk Metropolis-Hastings\nTarget: N(0, Sigma) with rho = 0.7, T = 10,000 iterations",
      outer = TRUE, cex = 1.0, font = 2, line = 1.5)

dev.off()
cat("\nSaved: figure_mcmc_convergence.png\n")
