"""
================================================================================
Figure 5.2: MCMC Convergence Diagnostics
================================================================================
6-panel figure: trace plots, ACF, and Geweke diagnostic
for well-tuned vs. poorly-tuned Random Walk MH.

Author: Alessia Paccagnini
Textbook: Macroeconometrics

NOTE: Requires mcmc_chain_good.csv and mcmc_chain_bad.csv
      generated by mcmc_generate_chains.py.
================================================================================
"""

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from scipy import stats

# ─────────────────────────────────────────────
# Load pre-generated chains
# ─────────────────────────────────────────────
chain_good = np.loadtxt('mcmc_chain_good.csv', delimiter=',', skiprows=1)
chain_bad  = np.loadtxt('mcmc_chain_bad.csv', delimiter=',', skiprows=1)
n_iter = len(chain_good)

# Acceptance rate from chain (count rows where values changed)
ar_good = np.mean(np.any(np.diff(chain_good, axis=0) != 0, axis=1))
ar_bad  = np.mean(np.any(np.diff(chain_bad, axis=0) != 0, axis=1))

mu = np.array([0.0, 0.0])

print(f"Well-tuned:   acceptance rate = {ar_good:.1%}")
print(f"Poorly tuned: acceptance rate = {ar_bad:.1%}")

# ─────────────────────────────────────────────
# ACF
# ─────────────────────────────────────────────
def compute_acf(x, max_lag=100):
    n = len(x)
    x_centered = x - np.mean(x)
    var = np.var(x)
    acf = np.zeros(max_lag + 1)
    for k in range(max_lag + 1):
        acf[k] = np.mean(x_centered[:n-k] * x_centered[k:]) / var if var > 0 else 0
    return acf

def compute_ess(acf_vals, n):
    tau = 1.0
    for k in range(1, len(acf_vals)):
        if acf_vals[k] < 0:
            break
        tau += 2 * acf_vals[k]
    return n / tau

max_lag = 100
acf_good = compute_acf(chain_good[:, 0], max_lag)
acf_bad = compute_acf(chain_bad[:, 0], max_lag)
ess_good = compute_ess(acf_good, n_iter)
ess_bad = compute_ess(acf_bad, n_iter)

print(f"Well-tuned:   ESS = {ess_good:.0f}")
print(f"Poorly tuned: ESS = {ess_bad:.0f}")

# ─────────────────────────────────────────────
# Geweke diagnostic (rolling window)
# ─────────────────────────────────────────────
def geweke_rolling(chain_1d, first_frac=0.1, window_starts=None):
    n = len(chain_1d)
    n_a = int(first_frac * n)
    chain_a = chain_1d[:n_a]
    mean_a = np.mean(chain_a)

    def spectral_var(x, max_bw=None):
        n_x = len(x)
        if max_bw is None:
            max_bw = int(np.sqrt(n_x))
        x_c = x - np.mean(x)
        gamma_0 = np.var(x_c)
        s = gamma_0
        for k in range(1, max_bw + 1):
            w = 1 - k / (max_bw + 1)
            gamma_k = np.mean(x_c[:n_x-k] * x_c[k:])
            s += 2 * w * gamma_k
        return s / n_x

    var_a = spectral_var(chain_a)

    if window_starts is None:
        n_b = int(0.5 * n)
        chain_b = chain_1d[n - n_b:]
        mean_b = np.mean(chain_b)
        var_b = spectral_var(chain_b)
        z = (mean_a - mean_b) / np.sqrt(var_a + var_b) if (var_a + var_b) > 0 else 0
        return z
    else:
        z_scores = np.zeros(len(window_starts))
        for i, start in enumerate(window_starts):
            chain_b = chain_1d[start:]
            mean_b = np.mean(chain_b)
            var_b = spectral_var(chain_b)
            denom = np.sqrt(var_a + var_b)
            z_scores[i] = (mean_a - mean_b) / denom if denom > 0 else 0
        return z_scores

window_starts = np.arange(int(0.2 * n_iter), int(0.8 * n_iter), 50)
geweke_good = geweke_rolling(chain_good[:, 0], first_frac=0.1, window_starts=window_starts)
geweke_bad = geweke_rolling(chain_bad[:, 0], first_frac=0.1, window_starts=window_starts)

z_good = geweke_rolling(chain_good[:, 0], first_frac=0.1)
z_bad = geweke_rolling(chain_bad[:, 0], first_frac=0.1)
print(f"\nGeweke Z (standard, first 10% vs last 50%):")
print(f"  Well-tuned:   Z = {z_good:.3f} (p = {2*(1-stats.norm.cdf(abs(z_good))):.3f})")
print(f"  Poorly tuned: Z = {z_bad:.3f} (p = {2*(1-stats.norm.cdf(abs(z_bad))):.3f})")

# ─────────────────────────────────────────────
# Figure: 3 rows × 2 columns
# ─────────────────────────────────────────────
fig = plt.figure(figsize=(14, 13))
gs = GridSpec(3, 2, hspace=0.40, wspace=0.25)

c_good = '#2171B5'
c_bad  = '#CB181D'

# ── Row 1: Trace plots ──
ax1 = fig.add_subplot(gs[0, 0])
ax1.plot(chain_good[:, 0], color=c_good, linewidth=0.3, alpha=0.8)
ax1.axhline(y=mu[0], color='black', linestyle='--', linewidth=1.0, alpha=0.5)
ax1.set_title(f'(a) Well-Tuned Trace Plot ($c = 1.70$)\nAcceptance rate: {ar_good:.1%}, ESS: {ess_good:.0f}',
              fontsize=11, fontweight='bold')
ax1.set_xlabel('Iteration')
ax1.set_ylabel(r'$\theta_1$')
ax1.set_xlim(0, n_iter)
ax1.set_ylim(-4, 4)

ax2 = fig.add_subplot(gs[0, 1])
ax2.plot(chain_bad[:, 0], color=c_bad, linewidth=0.3, alpha=0.8)
ax2.axhline(y=mu[0], color='black', linestyle='--', linewidth=1.0, alpha=0.5)
ax2.set_title(f'(b) Poorly-Tuned Trace Plot ($c = 0.05$)\nAcceptance rate: {ar_bad:.1%}, ESS: {ess_bad:.0f}',
              fontsize=11, fontweight='bold')
ax2.set_xlabel('Iteration')
ax2.set_ylabel(r'$\theta_1$')
ax2.set_xlim(0, n_iter)
ax2.set_ylim(-4, 4)

# ── Row 2: ACF ──
ax3 = fig.add_subplot(gs[1, 0])
ax3.bar(range(max_lag + 1), acf_good, width=1.0, color=c_good, alpha=0.7, edgecolor='none')
ax3.axhline(y=0, color='black', linewidth=0.8)
ax3.axhline(y=1.96/np.sqrt(n_iter), color='gray', linestyle='--', linewidth=0.8, alpha=0.6)
ax3.axhline(y=-1.96/np.sqrt(n_iter), color='gray', linestyle='--', linewidth=0.8, alpha=0.6)
ax3.set_title('(c) Well-Tuned Autocorrelation Function', fontsize=11, fontweight='bold')
ax3.set_xlabel('Lag')
ax3.set_ylabel('ACF')
ax3.set_xlim(0, max_lag)
ax3.set_ylim(-0.1, 1.05)

ax4 = fig.add_subplot(gs[1, 1])
ax4.bar(range(max_lag + 1), acf_bad, width=1.0, color=c_bad, alpha=0.7, edgecolor='none')
ax4.axhline(y=0, color='black', linewidth=0.8)
ax4.axhline(y=1.96/np.sqrt(n_iter), color='gray', linestyle='--', linewidth=0.8, alpha=0.6)
ax4.axhline(y=-1.96/np.sqrt(n_iter), color='gray', linestyle='--', linewidth=0.8, alpha=0.6)
ax4.set_title('(d) Poorly-Tuned Autocorrelation Function', fontsize=11, fontweight='bold')
ax4.set_xlabel('Lag')
ax4.set_ylabel('ACF')
ax4.set_xlim(0, max_lag)
ax4.set_ylim(-0.1, 1.05)

# ── Row 3: Geweke diagnostic ──
ax5 = fig.add_subplot(gs[2, 0])
ax5.plot(window_starts, geweke_good, color=c_good, linewidth=1.5)
ax5.axhline(y=0, color='black', linewidth=0.8)
ax5.axhline(y=1.96, color='gray', linestyle='--', linewidth=1.0, alpha=0.7)
ax5.axhline(y=-1.96, color='gray', linestyle='--', linewidth=1.0, alpha=0.7)
ax5.fill_between(window_starts, -1.96, 1.96, alpha=0.08, color='gray')
ax5.set_title(f'(e) Well-Tuned Geweke Diagnostic ($Z = {z_good:.2f}$)',
              fontsize=11, fontweight='bold')
ax5.set_xlabel('Start of comparison window')
ax5.set_ylabel('Geweke $Z$-score')
ax5.set_xlim(window_starts[0], window_starts[-1])
ax5.set_ylim(-4, 4)
ax5.text(window_starts[-1] - 200, 2.3, '95% critical values', fontsize=8, color='gray',
         ha='right', style='italic')

ax6 = fig.add_subplot(gs[2, 1])
ax6.plot(window_starts, geweke_bad, color=c_bad, linewidth=1.5)
ax6.axhline(y=0, color='black', linewidth=0.8)
ax6.axhline(y=1.96, color='gray', linestyle='--', linewidth=1.0, alpha=0.7)
ax6.axhline(y=-1.96, color='gray', linestyle='--', linewidth=1.0, alpha=0.7)
ax6.fill_between(window_starts, -1.96, 1.96, alpha=0.08, color='gray')
ax6.set_title(f'(f) Poorly-Tuned Geweke Diagnostic ($Z = {z_bad:.2f}$)',
              fontsize=11, fontweight='bold')
ax6.set_xlabel('Start of comparison window')
ax6.set_ylabel('Geweke $Z$-score')
ax6.set_xlim(window_starts[0], window_starts[-1])
ax6.set_ylim(-4, 4)
ax6.text(window_starts[-1] - 200, 2.3, '95% critical values', fontsize=8, color='gray',
         ha='right', style='italic')

fig.suptitle('MCMC Convergence Diagnostics: Random Walk Metropolis-Hastings\n'
             r'Target: $\mathcal{N}(\mathbf{0}, \Sigma)$ with $\rho = 0.7$, '
             f'$T = {n_iter:,}$ iterations',
             fontsize=13, fontweight='bold', y=1.01)

plt.savefig('figure_mcmc_convergence.png', dpi=200, bbox_inches='tight')
plt.close()
print("\nFigure saved: figure_mcmc_convergence.png")
