%% ========================================================================
%  Figure 5.2: MCMC Convergence Diagnostics
%  ========================================================================
%  6-panel figure: trace plots, ACF, and Geweke diagnostic
%  for well-tuned vs. poorly-tuned Random Walk MH.
%
%  Author: Alessia Paccagnini
%  Textbook: Macroeconometrics
%
%  NOTE: Requires mcmc_chain_good.csv and mcmc_chain_bad.csv
%        generated by mcmc_generate_chains.py.
%  ========================================================================
clear; clc; close all;

%% Load pre-generated chains
chain_good = readmatrix('mcmc_chain_good.csv');
chain_bad  = readmatrix('mcmc_chain_bad.csv');
n_iter = size(chain_good, 1);

% Acceptance rate from chain (count rows where values changed)
diffs_good = diff(chain_good);
ar_good = mean(any(diffs_good ~= 0, 2));
diffs_bad = diff(chain_bad);
ar_bad = mean(any(diffs_bad ~= 0, 2));

fprintf('Well-tuned:   acceptance rate = %.1f%%\n', 100 * ar_good);
fprintf('Poorly tuned: acceptance rate = %.1f%%\n', 100 * ar_bad);

%% ACF and ESS
max_lag  = 100;
acf_good = compute_acf(chain_good(:,1), max_lag);
acf_bad  = compute_acf(chain_bad(:,1), max_lag);
ess_good = compute_ess(acf_good, n_iter);
ess_bad  = compute_ess(acf_bad, n_iter);

fprintf('Well-tuned:   ESS = %.0f\n', ess_good);
fprintf('Poorly tuned: ESS = %.0f\n', ess_bad);

%% Geweke diagnostic
window_starts = floor(0.2*n_iter):50:floor(0.8*n_iter);
geweke_good   = geweke_rolling(chain_good(:,1), 0.1, window_starts);
geweke_bad    = geweke_rolling(chain_bad(:,1), 0.1, window_starts);

z_good = geweke_rolling(chain_good(:,1), 0.1, []);
z_bad  = geweke_rolling(chain_bad(:,1), 0.1, []);

fprintf('\nGeweke Z (first 10%% vs last 50%%):\n');
fprintf('  Well-tuned:   Z = %.3f (p = %.3f)\n', z_good, 2*(1-normcdf(abs(z_good))));
fprintf('  Poorly tuned: Z = %.3f (p = %.3f)\n', z_bad, 2*(1-normcdf(abs(z_bad))));

%% Figure: 3 rows x 2 columns
c_good = [33 113 181]/255;   % #2171B5
c_bad  = [203 24 29]/255;    % #CB181D

figure('Position', [50 50 1400 1300]);

% Row 1: Trace plots
subplot(3,2,1);
plot(chain_good(:,1), 'Color', [c_good, 0.8], 'LineWidth', 0.3); hold on;
yline(0, 'k--', 'LineWidth', 1.0);
title(sprintf('(a) Well-Tuned Trace Plot (c = 1.70)\nAcceptance rate: %.1f%%, ESS: %.0f', ...
    100*ar_good, ess_good), 'FontWeight', 'bold');
xlabel('Iteration'); ylabel('\theta_1');
xlim([1 n_iter]); ylim([-4 4]);

subplot(3,2,2);
plot(chain_bad(:,1), 'Color', [c_bad, 0.8], 'LineWidth', 0.3); hold on;
yline(0, 'k--', 'LineWidth', 1.0);
title(sprintf('(b) Poorly-Tuned Trace Plot (c = 0.05)\nAcceptance rate: %.1f%%, ESS: %.0f', ...
    100*ar_bad, ess_bad), 'FontWeight', 'bold');
xlabel('Iteration'); ylabel('\theta_1');
xlim([1 n_iter]); ylim([-4 4]);

% Row 2: ACF
subplot(3,2,3);
bar(0:max_lag, acf_good, 1.0, 'FaceColor', c_good, 'FaceAlpha', 0.7, 'EdgeColor', 'none'); hold on;
yline(0, 'k-', 'LineWidth', 0.8);
yline(1.96/sqrt(n_iter), '--', 'Color', [0.5 0.5 0.5]);
yline(-1.96/sqrt(n_iter), '--', 'Color', [0.5 0.5 0.5]);
title('(c) Well-Tuned Autocorrelation Function', 'FontWeight', 'bold');
xlabel('Lag'); ylabel('ACF');
xlim([0 max_lag]); ylim([-0.1 1.05]);

subplot(3,2,4);
bar(0:max_lag, acf_bad, 1.0, 'FaceColor', c_bad, 'FaceAlpha', 0.7, 'EdgeColor', 'none'); hold on;
yline(0, 'k-', 'LineWidth', 0.8);
yline(1.96/sqrt(n_iter), '--', 'Color', [0.5 0.5 0.5]);
yline(-1.96/sqrt(n_iter), '--', 'Color', [0.5 0.5 0.5]);
title('(d) Poorly-Tuned Autocorrelation Function', 'FontWeight', 'bold');
xlabel('Lag'); ylabel('ACF');
xlim([0 max_lag]); ylim([-0.1 1.05]);

% Row 3: Geweke diagnostic
subplot(3,2,5);
fill([window_starts(1) window_starts(end) window_starts(end) window_starts(1)], ...
     [-1.96 -1.96 1.96 1.96], [0.8 0.8 0.8], 'FaceAlpha', 0.15, 'EdgeColor', 'none'); hold on;
plot(window_starts, geweke_good, 'Color', c_good, 'LineWidth', 1.5);
yline(0, 'k-', 'LineWidth', 0.8);
yline(1.96, '--', 'Color', [0.5 0.5 0.5]);
yline(-1.96, '--', 'Color', [0.5 0.5 0.5]);
title(sprintf('(e) Well-Tuned Geweke Diagnostic (Z = %.2f)', z_good), 'FontWeight', 'bold');
xlabel('Start of comparison window'); ylabel('Geweke Z-score');
xlim([window_starts(1) window_starts(end)]); ylim([-4 4]);
text(window_starts(end)-200, 2.3, '95% critical values', ...
    'FontSize', 8, 'Color', [0.4 0.4 0.4], 'HorizontalAlignment', 'right', 'FontAngle', 'italic');

subplot(3,2,6);
fill([window_starts(1) window_starts(end) window_starts(end) window_starts(1)], ...
     [-1.96 -1.96 1.96 1.96], [0.8 0.8 0.8], 'FaceAlpha', 0.15, 'EdgeColor', 'none'); hold on;
plot(window_starts, geweke_bad, 'Color', c_bad, 'LineWidth', 1.5);
yline(0, 'k-', 'LineWidth', 0.8);
yline(1.96, '--', 'Color', [0.5 0.5 0.5]);
yline(-1.96, '--', 'Color', [0.5 0.5 0.5]);
title(sprintf('(f) Poorly-Tuned Geweke Diagnostic (Z = %.2f)', z_bad), 'FontWeight', 'bold');
xlabel('Start of comparison window'); ylabel('Geweke Z-score');
xlim([window_starts(1) window_starts(end)]); ylim([-4 4]);
text(window_starts(end)-200, 2.3, '95% critical values', ...
    'FontSize', 8, 'Color', [0.4 0.4 0.4], 'HorizontalAlignment', 'right', 'FontAngle', 'italic');

sgtitle({'MCMC Convergence Diagnostics: Random Walk Metropolis-Hastings', ...
         'Target: N(0, \Sigma) with \rho = 0.7, T = 10,000 iterations'}, ...
         'FontSize', 13, 'FontWeight', 'bold');

exportgraphics(gcf, 'figure_mcmc_convergence.png', 'Resolution', 200);
fprintf('\nSaved: figure_mcmc_convergence.png\n');


%% ========================================================================
%  LOCAL FUNCTIONS
%  ========================================================================

function acf_vals = compute_acf(x, max_lag)
    n = length(x);
    x_c = x - mean(x);
    v = var(x_c, 1);  % population variance
    acf_vals = zeros(max_lag + 1, 1);
    for k = 0:max_lag
        acf_vals(k+1) = mean(x_c(1:n-k) .* x_c(k+1:n)) / v;
    end
end


function ess = compute_ess(acf_vals, n)
    tau = 1.0;
    for k = 2:length(acf_vals)
        if acf_vals(k) < 0
            break;
        end
        tau = tau + 2 * acf_vals(k);
    end
    ess = n / tau;
end


function z = geweke_rolling(chain_1d, first_frac, window_starts)
    n = length(chain_1d);
    n_a = floor(first_frac * n);
    chain_a = chain_1d(1:n_a);
    mean_a = mean(chain_a);
    var_a = spectral_var(chain_a);

    if isempty(window_starts)
        n_b = floor(0.5 * n);
        chain_b = chain_1d(n - n_b + 1:n);
        mean_b = mean(chain_b);
        var_b = spectral_var(chain_b);
        denom = sqrt(var_a + var_b);
        if denom > 0
            z = (mean_a - mean_b) / denom;
        else
            z = 0;
        end
    else
        z = zeros(length(window_starts), 1);
        for i = 1:length(window_starts)
            chain_b = chain_1d(window_starts(i):n);
            mean_b = mean(chain_b);
            var_b = spectral_var(chain_b);
            denom = sqrt(var_a + var_b);
            if denom > 0
                z(i) = (mean_a - mean_b) / denom;
            end
        end
    end
end


function s = spectral_var(x)
    n_x = length(x);
    max_bw = floor(sqrt(n_x));
    x_c = x - mean(x);
    gamma_0 = var(x_c, 1);
    s = gamma_0;
    for k = 1:max_bw
        w = 1 - k / (max_bw + 1);
        gamma_k = mean(x_c(1:n_x-k) .* x_c(k+1:n_x));
        s = s + 2 * w * gamma_k;
    end
    s = s / n_x;
end
