%% Example 2: Spurious Regression and Error Correction Models
% =========================================================================
% This example demonstrates:
% 1. The spurious regression problem with independent I(1) series
% 2. Cointegration testing using Engle-Granger method
% 3. Error Correction Model estimation and interpretation
%
% Note: random draws differ from Python due to different RNG implementations.
% Required Toolboxes: Econometrics Toolbox, Statistics Toolbox
% Author: Alessia Paccagnini
% Textbook: Macroeconometrics
% =========================================================================

clear; clc; close all;

% =========================================================================
% DATA SOURCE SWITCH
% Set USE_PYTHON_DATA = true  → load ex2_data.csv (generated by Python)
%                                 Part B results match the textbook exactly
% Set USE_PYTHON_DATA = false → simulate data in MATLAB (rng(456))
%                                 results follow same DGP but differ numerically
% Note: Part A (spurious regression) always uses MATLAB RNG — exact numbers
%       don't matter there since any two independent random walks make the point.
% =========================================================================
USE_PYTHON_DATA = true;   % <-- CHANGE THIS FLAG

n = 200;

fprintf('======================================================================\n');
fprintf('EXAMPLE 2: SPURIOUS REGRESSION AND ERROR CORRECTION MODELS\n');
fprintf('======================================================================\n');

%% Part A: SPURIOUS REGRESSION
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('PART A: SPURIOUS REGRESSION PROBLEM\n');
fprintf('======================================================================\n');

% Generate two INDEPENDENT random walks
% Part A is always simulated in MATLAB - any two independent random walks
% demonstrate the spurious regression problem equally well.
rng(123);
eps1 = randn(n, 1);
eps2 = randn(n, 1);

y_spurious = cumsum(eps1);  % Random walk 1
x_spurious = cumsum(eps2);  % Random walk 2 (independent!)

fprintf('\nData Generation:\n');
fprintf('    y_t = y_{t-1} + e1_t  (Random Walk)\n');
fprintf('    x_t = x_{t-1} + e2_t  (Random Walk, INDEPENDENT of y)\n');
fprintf('    By construction, there is NO relationship between y and x!\n');

% Plot the spurious data
figure('Position', [100, 100, 1000, 700]);

subplot(2,2,1);
plot(y_spurious, 'b-', 'LineWidth', 0.8);
hold on;
plot(x_spurious, 'r-', 'LineWidth', 0.8);
title('Two Independent Random Walks', 'FontWeight', 'bold');
legend('y (random walk)', 'x (random walk)');
grid on;

subplot(2,2,2);
scatter(x_spurious, y_spurious, 20, 'filled', 'MarkerFaceAlpha', 0.5);
xlabel('x'); ylabel('y');
title('Scatter Plot (Spurious Correlation)', 'FontWeight', 'bold');
grid on;

% Run the spurious regression
X_spur = [ones(n,1), x_spurious];
[b_spur, ~, resid_spur, ~, stats_spur] = regress(y_spurious, X_spur);

% Calculate t-statistic manually
se_beta = sqrt(stats_spur(4) * inv(X_spur' * X_spur));
t_stat = b_spur(2) / se_beta(2,2);
p_val = 2 * (1 - tcdf(abs(t_stat), n-2));

% Durbin-Watson statistic
dw = sum(diff(resid_spur).^2) / sum(resid_spur.^2);

fprintf('\n--------------------------------------------------\n');
fprintf('SPURIOUS REGRESSION: y_t = a + b*x_t + u_t\n');
fprintf('--------------------------------------------------\n');
fprintf('    b coefficient: %.4f\n', b_spur(2));
fprintf('    t-statistic:   %.4f\n', t_stat);
fprintf('    p-value:       %.6f\n', p_val);
fprintf('    R-squared:     %.4f\n', stats_spur(1));
fprintf('    Durbin-Watson: %.4f\n', dw);

fprintf('\n    WARNING: The regression appears highly significant!\n');
fprintf('    But we KNOW y and x are independent by construction!\n');
fprintf('    This is the SPURIOUS REGRESSION problem.\n');

% Granger-Newbold rule of thumb
fprintf('\n    Granger-Newbold rule: R^2 > DW suggests spurious regression\n');
fprintf('    R^2 = %.3f, DW = %.3f -> ', stats_spur(1), dw);
if stats_spur(1) > dw
    fprintf('SPURIOUS!\n');
else
    fprintf('OK\n');
end

subplot(2,2,3);
plot(resid_spur, 'g-', 'LineWidth', 0.8);
yline(0, 'k--');
title('Residuals from Spurious Regression', 'FontWeight', 'bold');
ylabel('Residuals');
grid on;

% Test residuals for unit root
[h_adf, pval_adf, stat_adf] = adftest(resid_spur);
fprintf('\n    ADF test on residuals: stat = %.3f, p-value = %.3f\n', stat_adf, pval_adf);
if h_adf == 1
    fprintf('    Residuals are stationary -> Valid regression\n');
else
    fprintf('    Residuals are NON-STATIONARY -> Spurious!\n');
end

%% Part B: COINTEGRATION
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('PART B: COINTEGRATION - A GENUINE LONG-RUN RELATIONSHIP\n');
fprintf('======================================================================\n');

% Generate COINTEGRATED series (e.g., consumption and income)
beta_true  = 0.85;
alpha_true = 15;

if USE_PYTHON_DATA
    fprintf('Loading Python-generated data (ex2_data.csv)...\n');
    fprintf('Results will match the textbook exactly.\n\n');
    T = readtable('ex2_data.csv');
    income      = T.income;
    consumption = T.consumption;
else
    fprintf('Simulating cointegrated data in MATLAB (rng=456)...\n');
    fprintf('Note: numerical results differ from textbook due to different RNG.\n\n');
    rng(456);
    income_shocks = 0.5 + randn(n, 1);   % drift=0.5, sigma=1.0
    income        = 100 + cumsum(income_shocks);
    stationary_error = zeros(n, 1);
    for t = 2:n
        stationary_error(t) = 0.6 * stationary_error(t-1) + 1.5*randn(1);
    end
    consumption = alpha_true + beta_true * income + stationary_error;
end

fprintf('\nData Generation (Permanent Income Hypothesis):\n');
fprintf('    income_t = income_{t-1} + 0.5 + e_t  (Random Walk with drift)\n');
fprintf('    consumption_t = %.0f + %.2f*income_t + u_t  (Cointegrated)\n', alpha_true, beta_true);
fprintf('    where u_t = 0.6*u_{t-1} + v_t is a stationary AR(1) process\n');
fprintf('    TRUE cointegrating vector: (1, -%.2f)\n', beta_true);

subplot(2,2,4);
plot(income, 'b-', 'LineWidth', 0.8);
hold on;
plot(consumption, 'r-', 'LineWidth', 0.8);
title('Cointegrated Series (Income & Consumption)', 'FontWeight', 'bold');
legend('Income', 'Consumption');
grid on;

sgtitle('Spurious Regression vs Cointegration', 'FontSize', 14, 'FontWeight', 'bold');
saveas(gcf, 'example2_spurious_coint_matlab.png');

% Unit root tests on levels
fprintf('\n--------------------------------------------------\n');
fprintf('STEP 1: Test for Unit Roots in Levels\n');
fprintf('--------------------------------------------------\n');

[h_inc, pval_inc, stat_inc] = adftest(income);
[h_cons, pval_cons, stat_cons] = adftest(consumption);

fprintf('    Income:      ADF stat = %.3f, p-value = %.3f -> I(1)\n', stat_inc, pval_inc);
fprintf('    Consumption: ADF stat = %.3f, p-value = %.3f -> I(1)\n', stat_cons, pval_cons);

% Engle-Granger cointegration test
fprintf('\n--------------------------------------------------\n');
fprintf('STEP 2: Engle-Granger Cointegration Test\n');
fprintf('--------------------------------------------------\n');

% Step 2a: Estimate cointegrating regression
X_coint = [ones(n,1), income];
[b_coint, ~, resid_coint] = regress(consumption, X_coint);

fprintf('\nCointegrating Regression: consumption_t = a + b*income_t + z_t\n');
fprintf('    a (constant): %.4f\n', b_coint(1));
fprintf('    b (income):   %.4f (true value = %.1f)\n', b_coint(2), beta_true);

% Calculate R-squared
ss_tot = sum((consumption - mean(consumption)).^2);
ss_res = sum(resid_coint.^2);
r2_coint = 1 - ss_res/ss_tot;
fprintf('    R-squared:    %.4f\n', r2_coint);

% Step 2b: Test residuals for stationarity
[h_coint, pval_coint, stat_coint, cval_coint] = adftest(resid_coint);

fprintf('\nADF Test on Cointegrating Residuals:\n');
fprintf('    Test statistic: %.4f\n', stat_coint);
fprintf('    p-value:        %.4f\n', pval_coint);
fprintf('    Critical Value (5%%): %.2f\n', cval_coint);

fprintf('\n    Note: Use Engle-Granger critical values (more stringent):\n');
fprintf('    For 2 variables: 1%%: -3.90, 5%%: -3.34, 10%%: -3.04\n');

if stat_coint < -3.34
    fprintf('\n    CONCLUSION: Residuals are stationary -> Series are COINTEGRATED\n');
else
    fprintf('\n    CONCLUSION: Cannot reject unit root -> No cointegration\n');
end

%% Part C: ERROR CORRECTION MODEL
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('PART C: ERROR CORRECTION MODEL (ECM)\n');
fprintf('======================================================================\n');

% Create ECM variables
dc = diff(consumption);           % Delta c_t
dy = diff(income);                % Delta y_t
ec_term = resid_coint(1:end-1);   % z_{t-1} = c_{t-1} - a - b*y_{t-1}

% Estimate ECM: Delta c_t = gamma + alpha*z_{t-1} + delta*Delta y_t + e_t
X_ecm = [ones(n-1, 1), ec_term, dy];
[b_ecm, ~, resid_ecm, ~, stats_ecm] = regress(dc, X_ecm);

% Calculate standard errors and t-statistics
mse_ecm = sum(resid_ecm.^2) / (n - 1 - 3);
var_b = mse_ecm * inv(X_ecm' * X_ecm);
se_ecm = sqrt(diag(var_b));
t_ecm = b_ecm ./ se_ecm;

fprintf('\nECM Specification:\n');
fprintf('    Delta c_t = gamma + alpha*(c_{t-1} - b*y_{t-1}) + delta*Delta y_t + e_t\n');
fprintf('\nEstimation Results:\n');
fprintf('------------------------------------------------------------\n');
fprintf('%-15s %10s %10s %10s\n', 'Parameter', 'Estimate', 'Std.Err', 't-stat');
fprintf('------------------------------------------------------------\n');
fprintf('%-15s %10.4f %10.4f %10.4f\n', 'Constant (g)', b_ecm(1), se_ecm(1), t_ecm(1));
fprintf('%-15s %10.4f %10.4f %10.4f\n', 'EC term (a)', b_ecm(2), se_ecm(2), t_ecm(2));
fprintf('%-15s %10.4f %10.4f %10.4f\n', 'Delta y (d)', b_ecm(3), se_ecm(3), t_ecm(3));
fprintf('------------------------------------------------------------\n');

alpha_ec = b_ecm(2);
fprintf('\n    Error Correction Coefficient (alpha): %.4f\n', alpha_ec);
fprintf('    Standard Error: %.4f\n', se_ecm(2));
fprintf('    t-statistic: %.4f\n', t_ecm(2));

if alpha_ec < 0
    fprintf('\n    alpha < 0: System corrects toward equilibrium\n');
    half_life = log(0.5) / log(1 + alpha_ec);
    fprintf('    Speed of adjustment: %.1f%% of disequilibrium corrected per period\n', abs(alpha_ec)*100);
    fprintf('    Half-life of adjustment: %.1f periods\n', half_life);
else
    fprintf('\n    alpha > 0: System is explosive (should not happen with cointegration)\n');
end

fprintf('\n    Short-run effect of income (delta): %.4f\n', b_ecm(3));
fprintf('    Long-run effect of income (beta): %.4f\n', b_coint(2));

% Diagnostic plots for ECM
figure('Position', [100, 100, 900, 700]);

subplot(2,2,1);
plot(resid_coint, 'b-', 'LineWidth', 0.8);
yline(0, 'r--', 'LineWidth', 1);
title('Equilibrium Error (z_t = c_t - a - b*y_t)', 'FontWeight', 'bold');
ylabel('Deviation from equilibrium');
grid on;

subplot(2,2,2);
plot(resid_ecm, 'g-', 'LineWidth', 0.8);
yline(0, 'r--', 'LineWidth', 1);
title('ECM Residuals', 'FontWeight', 'bold');
grid on;

subplot(2,2,3);
fitted_ecm = X_ecm * b_ecm;
plot(dc, 'b-', 'LineWidth', 0.8);
hold on;
plot(fitted_ecm, 'r--', 'LineWidth', 0.8);
title('Actual vs Fitted Values', 'FontWeight', 'bold');
legend('Actual \Delta c', 'Fitted');
grid on;

subplot(2,2,4);
scatter(ec_term, dc, 20, 'filled', 'MarkerFaceAlpha', 0.5);
hold on;
xline(0, 'k--', 'Alpha', 0.5);
yline(0, 'k--', 'Alpha', 0.5);
% Add regression line
z_range = linspace(min(ec_term), max(ec_term), 100);
plot(z_range, alpha_ec * z_range + b_ecm(1), 'r-', 'LineWidth', 2);
xlabel('Equilibrium Error (z_{t-1})');
ylabel('\Delta c_t');
title('Error Correction Mechanism', 'FontWeight', 'bold');
legend('Data', '', '', sprintf('\\alpha = %.3f', alpha_ec), 'Location', 'best');
grid on;

sgtitle('Error Correction Model Diagnostics', 'FontSize', 14, 'FontWeight', 'bold');
saveas(gcf, 'example2_ecm_matlab.png');

%% Summary
fprintf('\n======================================================================\n');
fprintf('SUMMARY\n');
fprintf('======================================================================\n');
fprintf('\n1. SPURIOUS REGRESSION: Independent I(1) series can produce highly\n');
fprintf('   significant but meaningless regression results. Always test for\n');
fprintf('   unit roots and cointegration!\n\n');
fprintf('2. COINTEGRATION: When I(1) series share a common stochastic trend,\n');
fprintf('   their linear combination is stationary. This implies a genuine\n');
fprintf('   long-run equilibrium relationship.\n\n');
fprintf('3. ERROR CORRECTION MODEL: Cointegrated variables adjust toward their\n');
fprintf('   long-run equilibrium. The ECM captures both:\n');
fprintf('   - Short-run dynamics (Delta y effect)\n');
fprintf('   - Long-run equilibrium adjustment (error correction term)\n\n');
fprintf('   The speed of adjustment coefficient (alpha < 0) tells us how quickly\n');
fprintf('   deviations from equilibrium are corrected.\n');
fprintf('======================================================================\n');
