# =============================================================================
# Example 1: ARIMA Model Selection Using Box-Jenkins Methodology
# =============================================================================
# This example demonstrates the three-stage Box-Jenkins approach:
# 1. Identification: Plot data, test for stationarity, examine ACF/PACF
# 2. Estimation: Fit ARIMA model
# 3. Diagnostic Checking: Analyze residuals
#
# Required Packages: tseries, forecast, lmtest
# Author: Alessia Paccagnini
# Textbook: Macroeconometrics
# =============================================================================

# Install packages if needed
# install.packages(c("tseries", "forecast", "lmtest", "FinTS"))

library(tseries)
library(forecast)
library(lmtest)

# =============================================================================
# DATA SOURCE SWITCH
# Set USE_PYTHON_DATA <- TRUE  -> load ex1_data.csv (generated by Python)
#                                  results match the textbook exactly
# Set USE_PYTHON_DATA <- FALSE -> simulate data in R (set.seed(42))
#                                  results follow same DGP but differ numerically
# =============================================================================
USE_PYTHON_DATA <- TRUE   # <-- CHANGE THIS FLAG

# =============================================================================
# Step 0: Simulated Data (ARMA(2,1) process)
# =============================================================================
# True parameters: phi1=0.4, phi2=-0.2, theta1=0.3, c=0.5
n           <- 200
phi1_true   <- 0.4
phi2_true   <- -0.2
theta1_true <- 0.3
c_true      <- 0.5

if (USE_PYTHON_DATA) {
  cat("Loading Python-generated data (ex1_data.csv)...\n")
  cat("Results will match the textbook exactly.\n\n")
  data_ex1 <- read.csv("ex1_data.csv")
  y <- data_ex1$y
} else {
  cat("Simulating data in R (set.seed=42)...\n")
  cat("Note: numerical results differ from textbook due to different RNG.\n\n")
  set.seed(42)
  eps <- rnorm(n)
  y   <- numeric(n)
  for (t in 3:n) {
    y[t] <- c_true + phi1_true*y[t-1] + phi2_true*y[t-2] + eps[t] + theta1_true*eps[t-1]
  }
}

# Create time series object
gdp_growth <- ts(y, start = c(1970, 1), frequency = 4)

cat("======================================================================\n")
cat("EXAMPLE 1: ARIMA MODEL SELECTION - BOX-JENKINS METHODOLOGY\n")
cat("======================================================================\n")
cat(sprintf("\nTrue DGP: y_t = %.1f + %.1f*y_{t-1} + %.1f*y_{t-2} + e_t + %.1f*e_{t-1}\n",
            c_true, phi1_true, phi2_true, theta1_true))

# =============================================================================
# Stage 1: IDENTIFICATION
# =============================================================================
cat("\n======================================================================\n")
cat("STAGE 1: IDENTIFICATION\n")
cat("======================================================================\n")

# 1.1 Visual Inspection
png("example1_identification_R.png", width = 900, height = 700)
par(mfrow = c(3, 1), mar = c(4, 4, 3, 2))

# Time series plot
plot(gdp_growth, type = "l", col = "blue", lwd = 0.8,
     main = "GDP Growth Rate (Simulated)", ylab = "Percent", xlab = "")
abline(h = mean(gdp_growth), col = "red", lty = 2, lwd = 1.5)
legend("topright", legend = sprintf("Mean = %.2f", mean(gdp_growth)), 
       col = "red", lty = 2, bty = "n")
grid()

# ACF
acf(gdp_growth, lag.max = 20, main = "Autocorrelation Function (ACF)")

# PACF
pacf(gdp_growth, lag.max = 20, main = "Partial Autocorrelation Function (PACF)")

dev.off()

cat("\n1.1 Visual Inspection:\n")
cat("    - Time series plot shows fluctuations around a constant mean\n")
cat("    - No obvious trend detected\n")
cat("    - See 'example1_identification_R.png' for ACF/PACF plots\n")

# 1.2 Unit Root Tests
cat("\n1.2 Unit Root Tests:\n")

# ADF Test
adf_result <- adf.test(gdp_growth, alternative = "stationary")
cat("\n    ADF Test (H0: unit root):\n")
cat(sprintf("    Test Statistic: %.4f\n", adf_result$statistic))
cat(sprintf("    p-value: %.4f\n", adf_result$p.value))
if (adf_result$p.value < 0.05) {
  cat("    Conclusion: Reject H0 - Series is stationary\n")
} else {
  cat("    Conclusion: Fail to reject H0 - Series has unit root\n")
}

# KPSS Test
kpss_result <- kpss.test(gdp_growth, null = "Level")
cat("\n    KPSS Test (H0: stationarity):\n")
cat(sprintf("    Test Statistic: %.4f\n", kpss_result$statistic))
cat(sprintf("    p-value: %.4f\n", kpss_result$p.value))
if (kpss_result$p.value > 0.05) {
  cat("    Conclusion: Fail to reject H0 - Series is stationary\n")
} else {
  cat("    Conclusion: Reject H0 - Series is non-stationary\n")
}

cat("\n    Combined inference: Both tests suggest the series is STATIONARY (d=0)\n")

# 1.3 ACF/PACF interpretation
cat("\n1.3 ACF/PACF Interpretation:\n")
cat("    - ACF: Gradual decay suggests AR component\n")
cat("    - PACF: Significant spikes at lags 1 and 2, then cuts off\n")
cat("    - Tentative model: AR(2) or ARMA(2,1)\n")

# =============================================================================
# Stage 2: ESTIMATION
# =============================================================================
cat("\n======================================================================\n")
cat("STAGE 2: ESTIMATION\n")
cat("======================================================================\n")

# Define models to try
models_to_try <- list(
  c(1, 0, 0),
  c(2, 0, 0),
  c(1, 0, 1),
  c(2, 0, 1),
  c(2, 0, 2)
)

model_names <- c("ARIMA(1,0,0)", "ARIMA(2,0,0)", "ARIMA(1,0,1)", 
                 "ARIMA(2,0,1)", "ARIMA(2,0,2)")

cat("\n2.1 Model Comparison (AIC/BIC):\n")
cat("--------------------------------------------------\n")
cat(sprintf("%-15s %-12s %-12s\n", "Model", "AIC", "BIC"))
cat("--------------------------------------------------\n")

results <- data.frame(
  model = character(),
  aic = numeric(),
  bic = numeric(),
  stringsAsFactors = FALSE
)

fitted_models <- list()

for (i in seq_along(models_to_try)) {
  order <- models_to_try[[i]]
  name <- model_names[i]
  
  tryCatch({
    fit <- Arima(gdp_growth, order = order, include.mean = TRUE)
    fitted_models[[name]] <- fit
    
    results <- rbind(results, data.frame(
      model = name,
      aic = AIC(fit),
      bic = BIC(fit),
      stringsAsFactors = FALSE
    ))
    
    cat(sprintf("%-15s %-12.2f %-12.2f\n", name, AIC(fit), BIC(fit)))
  }, error = function(e) {
    cat(sprintf("%-15s Failed to converge\n", name))
  })
}

cat("--------------------------------------------------\n")

# Select best model by BIC
best_idx <- which.min(results$bic)
best_model_name <- results$model[best_idx]
best_model <- fitted_models[[best_model_name]]

cat(sprintf("\nBest model by BIC: %s\n", best_model_name))

# Display estimation results
cat("\n2.2 Estimation Results for Best Model:\n")
cat("--------------------------------------------------\n")
print(summary(best_model))

# =============================================================================
# Stage 3: DIAGNOSTIC CHECKING
# =============================================================================
cat("\n======================================================================\n")
cat("STAGE 3: DIAGNOSTIC CHECKING\n")
cat("======================================================================\n")

# Get residuals
residuals_fit <- residuals(best_model)

# 3.1 Residual plots
png("example1_diagnostics_R.png", width = 900, height = 700)
par(mfrow = c(2, 2), mar = c(4, 4, 3, 2))

# Standardized residuals
plot(residuals_fit, type = "l", col = "blue", lwd = 0.8,
     main = "Standardized Residuals", ylab = "Residuals")
abline(h = 0, col = "red", lty = 2)
grid()

# Histogram
hist(residuals_fit, breaks = 25, freq = FALSE, col = "lightblue",
     main = "Histogram of Residuals", xlab = "Residuals")
curve(dnorm(x, mean = mean(residuals_fit), sd = sd(residuals_fit)),
      add = TRUE, col = "red", lwd = 2)

# ACF of residuals
acf(residuals_fit, lag.max = 20, main = "ACF of Residuals")

# Q-Q plot
qqnorm(residuals_fit, main = "Q-Q Plot")
qqline(residuals_fit, col = "red", lwd = 2)

dev.off()

cat("\n3.1 Residual Analysis:\n")
cat("    See 'example1_diagnostics_R.png' for diagnostic plots\n")

# 3.2 Ljung-Box test
cat("\n3.2 Ljung-Box Test for Residual Autocorrelation:\n")
lags_to_test <- c(5, 10, 15, 20)
dof_adjustment <- sum(models_to_try[[best_idx]][c(1, 3)])  # p + q

cat("    Lag     Q-stat      p-value\n")
cat("    ------------------------------\n")

all_pass <- TRUE
for (lag in lags_to_test) {
  lb_test <- Box.test(residuals_fit, lag = lag, type = "Ljung-Box", 
                      fitdf = dof_adjustment)
  cat(sprintf("    %2d      %.3f       %.4f\n", lag, lb_test$statistic, lb_test$p.value))
  if (lb_test$p.value < 0.05) {
    all_pass <- FALSE
  }
}

if (all_pass) {
  cat("\n    Conclusion: No significant autocorrelation in residuals (p > 0.05)\n")
  cat("    The model passes the diagnostic check!\n")
} else {
  cat("\n    Conclusion: Some autocorrelation remains - consider revising the model\n")
}

# 3.3 Summary statistics
cat("\n3.3 Residual Summary Statistics:\n")
cat(sprintf("    Mean: %.4f (should be ≈ 0)\n", mean(residuals_fit)))
cat(sprintf("    Std Dev: %.4f\n", sd(residuals_fit)))
cat(sprintf("    Skewness: %.4f (should be ≈ 0)\n", 
            sum((residuals_fit - mean(residuals_fit))^3) / (length(residuals_fit) * sd(residuals_fit)^3)))
cat(sprintf("    Kurtosis: %.4f (should be ≈ 3 for normal)\n",
            sum((residuals_fit - mean(residuals_fit))^4) / (length(residuals_fit) * sd(residuals_fit)^4)))

# Jarque-Bera test
jb_test <- jarque.bera.test(residuals_fit)
cat(sprintf("\n    Jarque-Bera test: statistic = %.2f, p-value = %.4f\n", 
            jb_test$statistic, jb_test$p.value))
if (jb_test$p.value > 0.05) {
  cat("    Residuals appear normally distributed\n")
} else {
  cat("    Residuals deviate from normality\n")
}

cat("\n======================================================================\n")
cat(sprintf("FINAL MODEL: %s\n", best_model_name))
cat("======================================================================\n")
