# =============================================================================
# Example 3: GARCH Models for Volatility Modeling
# =============================================================================
# This example demonstrates:
# 1. Testing for ARCH effects (ARCH-LM test)
# 2. Estimating GARCH(1,1) model
# 3. Interpreting results and volatility persistence
# 4. Comparing symmetric vs asymmetric GARCH models
#
# Required Packages: tseries, rugarch, FinTS
# Author: Alessia Paccagnini
# Textbook: Macroeconometrics
# =============================================================================

# Install packages if needed
# install.packages(c("tseries", "rugarch", "FinTS", "moments"))

library(tseries)
library(rugarch)
library(FinTS)
library(moments)

# =============================================================================
# DATA SOURCE SWITCH
# Set USE_PYTHON_DATA <- TRUE  -> load ex3_data.csv (generated by Python)
#                                  results match the textbook exactly
# Set USE_PYTHON_DATA <- FALSE -> simulate data in R (set.seed(456))
#                                  results follow same DGP but differ numerically
# =============================================================================
USE_PYTHON_DATA <- TRUE   # <-- CHANGE THIS FLAG

n <- 1000

# True parameters
omega_true <- 0.05
alpha_true <- 0.10
beta_true  <- 0.85

if (USE_PYTHON_DATA) {
  cat("Loading Python-generated data (ex3_data.csv)...\n")
  cat("Results will match the textbook exactly.\n\n")
  data_ex3 <- read.csv("ex3_data.csv")
  returns  <- data_ex3$returns
  sigma2   <- data_ex3$sigma2
} else {
  cat("Simulating GARCH data in R (set.seed=456)...\n")
  cat("Note: numerical results differ from textbook due to different RNG.\n\n")
  set.seed(456)
  returns   <- numeric(n)
  sigma2    <- numeric(n)
  sigma2[1] <- omega_true / (1 - alpha_true - beta_true)
  for (t in 2:n) {
    sigma2[t]  <- omega_true + alpha_true * returns[t-1]^2 + beta_true * sigma2[t-1]
    returns[t] <- sqrt(sigma2[t]) * rnorm(1)
  }
}

cat("\nTrue GARCH(1,1) parameters:\n")
cat(sprintf("    omega: %.2f\n", omega_true))
cat(sprintf("    alpha: %.2f\n", alpha_true))
cat(sprintf("    beta:  %.2f\n", beta_true))
cat(sprintf("    alpha + beta: %.2f (persistence)\n", alpha_true + beta_true))
cat(sprintf("    Unconditional variance: %.4f\n", omega_true / (1 - alpha_true - beta_true)))

# =============================================================================
# Visualize the data
# =============================================================================
png("example3_garch_data_R.png", width = 1000, height = 800)
par(mfrow = c(3, 1), mar = c(4, 4, 3, 2))

# Returns
plot(returns, type = "l", col = "blue", lwd = 0.5,
     main = "Simulated Stock Returns", ylab = "Returns", xlab = "Time")
abline(h = 0, col = "black", lwd = 0.5)
grid()

# Squared returns vs true variance
plot(returns^2, type = "l", col = rgb(1, 0, 0, 0.5), lwd = 0.5,
     main = "Volatility Clustering", ylab = "Squared Returns / Variance", xlab = "Time")
lines(sigma2, col = "blue", lwd = 1)
legend("topright", legend = c("Squared Returns", "True Conditional Variance"),
       col = c("red", "blue"), lty = 1, bty = "n")
grid()

# Distribution
hist(returns, breaks = 50, freq = FALSE, col = "lightblue",
     main = "Distribution of Returns (Fat Tails)", xlab = "Returns")
curve(dnorm(x, mean = mean(returns), sd = sd(returns)),
      add = TRUE, col = "red", lwd = 2)
legend("topright", legend = c("Returns", "Normal Distribution"),
       fill = c("lightblue", NA), border = c("black", NA),
       col = c(NA, "red"), lty = c(NA, 1), lwd = c(NA, 2), bty = "n")
grid()

dev.off()

cat("\nSee 'example3_garch_data_R.png' for visualization\n")

# Summary statistics
cat("\nSummary Statistics:\n")
cat(sprintf("    Mean:     %.4f\n", mean(returns)))
cat(sprintf("    Std Dev:  %.4f\n", sd(returns)))
cat(sprintf("    Skewness: %.4f\n", skewness(returns)))
cat(sprintf("    Kurtosis: %.4f (normal = 3)\n", kurtosis(returns)))
cat("    -> Excess kurtosis indicates fat tails (leptokurtosis)\n")

# =============================================================================
# Step 1: Test for ARCH Effects
# =============================================================================
cat("\n======================================================================\n")
cat("STEP 1: TESTING FOR ARCH EFFECTS (ARCH-LM Test)\n")
cat("======================================================================\n")

cat("\nARCH-LM Test: H0: No ARCH effects (homoskedasticity)\n")
cat("             H1: ARCH effects present (heteroskedasticity)\n")
cat("--------------------------------------------------\n")

lags_test <- c(1, 5, 10)
for (lag in lags_test) {
  arch_test <- ArchTest(returns, lags = lag)
  sig_str <- ""
  if (arch_test$p.value < 0.01) {
    sig_str <- "***"
  } else if (arch_test$p.value < 0.05) {
    sig_str <- "**"
  } else if (arch_test$p.value < 0.10) {
    sig_str <- "*"
  }
  cat(sprintf("    Lags = %2d: LM stat = %8.3f, p-value = %.6f %s\n", 
              lag, arch_test$statistic, arch_test$p.value, sig_str))
}
cat("--------------------------------------------------\n")
cat("    *** p<0.01, ** p<0.05, * p<0.10\n")
cat("\n    Strong evidence of ARCH effects -> GARCH modeling is appropriate\n")

# =============================================================================
# Step 2: Estimate GARCH(1,1) Model
# =============================================================================
cat("\n======================================================================\n")
cat("STEP 2: GARCH(1,1) ESTIMATION\n")
cat("======================================================================\n")

# Specify GARCH(1,1) model
spec_garch <- ugarchspec(
  variance.model = list(model = "sGARCH", garchOrder = c(1, 1)),
  mean.model = list(armaOrder = c(0, 0), include.mean = TRUE),
  distribution.model = "norm"
)

# Estimate
fit_garch <- ugarchfit(spec = spec_garch, data = returns, solver = "hybrid")

# Extract parameters
params_garch <- coef(fit_garch)
omega_hat <- params_garch["omega"]
alpha_hat <- params_garch["alpha1"]
beta_hat <- params_garch["beta1"]
persistence <- alpha_hat + beta_hat

cat("\nGARCH(1,1) Estimation Results:\n")
cat("--------------------------------------------------\n")
print(fit_garch)

cat("\nParameter Interpretation:\n")
cat(sprintf("    omega:    %.6f (intercept)\n", omega_hat))
cat(sprintf("    alpha:    %.4f (reaction to shocks)\n", alpha_hat))
cat(sprintf("    beta:     %.4f (volatility persistence)\n", beta_hat))
cat(sprintf("    alpha + beta: %.4f (total persistence)\n", persistence))

cat("\nComparison with True Values:\n")
cat(sprintf("    %-12s %10s %10s\n", "Parameter", "True", "Estimated"))
cat("    --------------------------------\n")
cat(sprintf("    %-12s %10.4f %10.4f\n", "omega", omega_true, omega_hat))
cat(sprintf("    %-12s %10.4f %10.4f\n", "alpha", alpha_true, alpha_hat))
cat(sprintf("    %-12s %10.4f %10.4f\n", "beta", beta_true, beta_hat))

# Unconditional variance and half-life
uncond_var <- omega_hat / (1 - alpha_hat - beta_hat)
half_life <- log(0.5) / log(persistence)

cat("\nImplied Quantities:\n")
cat(sprintf("    Unconditional variance: %.4f\n", uncond_var))
cat(sprintf("    Unconditional std dev:  %.4f\n", sqrt(uncond_var)))
cat(sprintf("    Half-life of shocks:    %.1f periods\n", half_life))
cat("    (Time for volatility shock to decay by 50%)\n")

# =============================================================================
# Step 3: Model Comparison (GARCH vs GJR-GARCH vs EGARCH)
# =============================================================================
cat("\n======================================================================\n")
cat("STEP 3: MODEL COMPARISON (Symmetric vs Asymmetric)\n")
cat("======================================================================\n")

# GJR-GARCH specification
spec_gjr <- ugarchspec(
  variance.model = list(model = "gjrGARCH", garchOrder = c(1, 1)),
  mean.model = list(armaOrder = c(0, 0), include.mean = TRUE),
  distribution.model = "norm"
)
fit_gjr <- ugarchfit(spec = spec_gjr, data = returns, solver = "hybrid")

# EGARCH specification
spec_egarch <- ugarchspec(
  variance.model = list(model = "eGARCH", garchOrder = c(1, 1)),
  mean.model = list(armaOrder = c(0, 0), include.mean = TRUE),
  distribution.model = "norm"
)
fit_egarch <- ugarchfit(spec = spec_egarch, data = returns, solver = "hybrid")

# Extract information criteria
ic_garch <- infocriteria(fit_garch)
ic_gjr <- infocriteria(fit_gjr)
ic_egarch <- infocriteria(fit_egarch)

cat("\nModel Comparison:\n")
cat("------------------------------------------------------------\n")
cat(sprintf("%-20s %12s %12s %12s\n", "Model", "Log-Lik", "AIC", "BIC"))
cat("------------------------------------------------------------\n")
cat(sprintf("%-20s %12.2f %12.4f %12.4f\n", "GARCH(1,1)", 
            likelihood(fit_garch), ic_garch[1], ic_garch[2]))
cat(sprintf("%-20s %12.2f %12.4f %12.4f\n", "GJR-GARCH(1,1,1)", 
            likelihood(fit_gjr), ic_gjr[1], ic_gjr[2]))
cat(sprintf("%-20s %12.2f %12.4f %12.4f\n", "EGARCH(1,1)", 
            likelihood(fit_egarch), ic_egarch[1], ic_egarch[2]))
cat("------------------------------------------------------------\n")

# Find best model by BIC
bic_values <- c(ic_garch[2], ic_gjr[2], ic_egarch[2])
model_names <- c("GARCH(1,1)", "GJR-GARCH(1,1,1)", "EGARCH(1,1)")
best_idx <- which.min(bic_values)
cat(sprintf("\nBest model by BIC: %s\n", model_names[best_idx]))

# Check asymmetry in GJR-GARCH
gamma_gjr <- coef(fit_gjr)["gamma1"]
cat(sprintf("\nGJR-GARCH asymmetry parameter (gamma): %.4f\n", gamma_gjr))
if (abs(gamma_gjr) > 0.01) {
  cat("    -> Evidence of asymmetric volatility (leverage effect)\n")
} else {
  cat("    -> No significant asymmetry (symmetric GARCH sufficient)\n")
}

# =============================================================================
# Step 4: Diagnostic Checking
# =============================================================================
cat("\n======================================================================\n")
cat("STEP 4: DIAGNOSTIC CHECKING\n")
cat("======================================================================\n")

# Get conditional variance and standardized residuals
cond_var <- sigma(fit_garch)^2
std_resid <- residuals(fit_garch, standardize = TRUE)

cat("\nStandardized Residuals Analysis:\n")
cat(sprintf("    Mean:     %.4f (should be ~ 0)\n", mean(std_resid)))
cat(sprintf("    Std Dev:  %.4f (should be ~ 1)\n", sd(std_resid)))
cat(sprintf("    Skewness: %.4f\n", skewness(std_resid)))
cat(sprintf("    Kurtosis: %.4f\n", kurtosis(std_resid)))

# ARCH-LM test on standardized residuals
cat("\nARCH-LM Test on Standardized Residuals:\n")
cat("    (Should show NO remaining ARCH effects)\n")
for (lag in c(5, 10)) {
  arch_test_resid <- ArchTest(as.numeric(std_resid), lags = lag)
  if (arch_test_resid$p.value > 0.05) {
    result_str <- "No ARCH effects (pass)"
  } else {
    result_str <- "ARCH effects remain (fail)"
  }
  cat(sprintf("    Lags = %2d: p-value = %.4f -> %s\n", 
              lag, arch_test_resid$p.value, result_str))
}

# Ljung-Box test on squared standardized residuals
cat("\nLjung-Box Test on Squared Standardized Residuals:\n")
for (lag in c(10, 20)) {
  lb_test <- Box.test(as.numeric(std_resid)^2, lag = lag, type = "Ljung-Box")
  cat(sprintf("    Lags = %2d: Q-stat = %.3f, p-value = %.4f\n", 
              lag, lb_test$statistic, lb_test$p.value))
}

# =============================================================================
# Visualization of results
# =============================================================================
png("example3_garch_results_R.png", width = 1000, height = 700)
par(mfrow = c(2, 2), mar = c(4, 4, 3, 2))

# Conditional volatility
cond_vol <- sigma(fit_garch)
plot(as.numeric(cond_vol), type = "l", col = "blue", lwd = 0.8,
     main = expression("Conditional Volatility ("*sigma[t]*")"),
     ylab = "Volatility", xlab = "Time")
lines(sqrt(sigma2), col = "red", lty = 2, lwd = 0.8)
legend("topright", legend = c("Estimated", "True"),
       col = c("blue", "red"), lty = c(1, 2), bty = "n")
grid()

# Returns with volatility bands
plot(returns, type = "l", col = "gray", lwd = 0.3,
     main = "Returns with 95% Volatility Bands",
     ylab = "Returns", xlab = "Time")
lines(2 * as.numeric(cond_vol), col = "red", lwd = 1)
lines(-2 * as.numeric(cond_vol), col = "red", lwd = 1)
legend("topright", legend = c("Returns", expression(pm*2*sigma~"bands")),
       col = c("gray", "red"), lty = 1, bty = "n")
grid()

# Standardized residuals
plot(as.numeric(std_resid), type = "l", col = "blue", lwd = 0.5,
     main = "Standardized Residuals",
     ylab = expression(z[t] == epsilon[t]/sigma[t]), xlab = "Time")
abline(h = 0, col = "black", lwd = 0.5)
abline(h = c(-2, 2), col = "red", lty = 2, lwd = 0.5)
grid()

# Q-Q plot
qqnorm(as.numeric(std_resid), main = "Q-Q Plot of Standardized Residuals",
       pch = 19, col = rgb(0, 0, 1, 0.3))
qqline(as.numeric(std_resid), col = "red", lwd = 2)

dev.off()

cat("\nSee 'example3_garch_results_R.png' for diagnostic plots\n")

# =============================================================================
# Summary
# =============================================================================
cat("\n======================================================================\n")
cat("SUMMARY\n")
cat("======================================================================\n")
cat("\nGARCH(1,1) Model Results:\n")
cat("-------------------------\n")
cat(sprintf("    sigma^2_t = %.4f + %.4f*e^2_{t-1} + %.4f*sigma^2_{t-1}\n",
            omega_hat, alpha_hat, beta_hat))
cat("\nKey Findings:\n")
cat("    - Strong ARCH effects detected (ARCH-LM test highly significant)\n")
cat(sprintf("    - High persistence (alpha + beta = %.3f): volatility shocks are long-lasting\n", 
            persistence))
cat(sprintf("    - Half-life of %.1f periods for volatility to return halfway to normal\n", 
            half_life))
cat("    - Model diagnostics: standardized residuals show no remaining ARCH effects\n")
cat("\nInterpretation:\n")
cat(sprintf("    - alpha = %.3f: %.1f%% of yesterday's squared shock affects today's variance\n",
            alpha_hat, alpha_hat * 100))
cat(sprintf("    - beta = %.3f: %.1f%% of yesterday's variance persists to today\n",
            beta_hat, beta_hat * 100))
cat("    - When alpha + beta is close to 1, the process is nearly integrated (IGARCH)\n")
cat("======================================================================\n")
