# =============================================================================
# Example 2: Spurious Regression and Error Correction Models
# =============================================================================
# This example demonstrates:
# 1. The spurious regression problem with independent I(1) series
# 2. Cointegration testing using Engle-Granger method
# 3. Error Correction Model estimation and interpretation
#
# Required Packages: tseries, lmtest, dynlm, urca
# Author: Alessia Paccagnini
# Textbook: Macroeconometrics
# =============================================================================

# Install packages if needed
# install.packages(c("tseries", "lmtest", "dynlm", "urca"))

library(tseries)
library(lmtest)
library(dynlm)
library(urca)

# =============================================================================
# DATA SOURCE SWITCH
# Set USE_PYTHON_DATA <- TRUE  -> load ex2_data.csv (generated by Python)
#                                  Part B results match the textbook exactly
# Set USE_PYTHON_DATA <- FALSE -> simulate data in R (set.seed(456))
#                                  results follow same DGP but differ numerically
# Note: Part A (spurious regression) always uses R RNG — exact numbers
#       don't matter there since any two independent random walks make the point.
# =============================================================================
USE_PYTHON_DATA <- TRUE   # <-- CHANGE THIS FLAG

n <- 200

cat("======================================================================\n")
cat("EXAMPLE 2: SPURIOUS REGRESSION AND ERROR CORRECTION MODELS\n")
cat("======================================================================\n")

# =============================================================================
# Part A: SPURIOUS REGRESSION
# =============================================================================
cat("\n======================================================================\n")
cat("PART A: SPURIOUS REGRESSION PROBLEM\n")
cat("======================================================================\n")

# Generate two INDEPENDENT random walks
# Using set.seed(123) - Part A is illustrative only (spurious by construction),
# so exact numerical match with Python is not required here.
set.seed(123)
eps1 <- rnorm(n)
eps2 <- rnorm(n)

y_spurious <- cumsum(eps1)  # Random walk 1
x_spurious <- cumsum(eps2)  # Random walk 2 (independent!)

cat("\nData Generation:\n")
cat("    y_t = y_{t-1} + e1_t  (Random Walk)\n")
cat("    x_t = x_{t-1} + e2_t  (Random Walk, INDEPENDENT of y)\n")
cat("    By construction, there is NO relationship between y and x!\n")

# Plot the spurious data
png("example2_spurious_coint_R.png", width = 1000, height = 700)
par(mfrow = c(2, 2), mar = c(4, 4, 3, 2))

# Two random walks
plot(y_spurious, type = "l", col = "blue", lwd = 0.8,
     main = "Two Independent Random Walks", ylab = "Value", xlab = "Time")
lines(x_spurious, col = "red", lwd = 0.8)
legend("topleft", legend = c("y (random walk)", "x (random walk)"),
       col = c("blue", "red"), lty = 1, bty = "n")
grid()

# Scatter plot
plot(x_spurious, y_spurious, pch = 19, col = rgb(0, 0, 1, 0.5),
     main = "Scatter Plot (Spurious Correlation)", xlab = "x", ylab = "y")
grid()

# Run the spurious regression
spurious_model <- lm(y_spurious ~ x_spurious)
spurious_summary <- summary(spurious_model)

# Durbin-Watson statistic
dw_test <- dwtest(spurious_model)
dw <- dw_test$statistic

cat("\n--------------------------------------------------\n")
cat("SPURIOUS REGRESSION: y_t = a + b*x_t + u_t\n")
cat("--------------------------------------------------\n")
cat(sprintf("    b coefficient: %.4f\n", coef(spurious_model)[2]))
cat(sprintf("    t-statistic:   %.4f\n", spurious_summary$coefficients[2, 3]))
cat(sprintf("    p-value:       %.6f\n", spurious_summary$coefficients[2, 4]))
cat(sprintf("    R-squared:     %.4f\n", spurious_summary$r.squared))
cat(sprintf("    Durbin-Watson: %.4f\n", dw))

cat("\n    WARNING: The regression appears highly significant!\n")
cat("    But we KNOW y and x are independent by construction!\n")
cat("    This is the SPURIOUS REGRESSION problem.\n")

# Granger-Newbold rule of thumb
cat("\n    Granger-Newbold rule: R^2 > DW suggests spurious regression\n")
cat(sprintf("    R^2 = %.3f, DW = %.3f -> ", spurious_summary$r.squared, dw))
if (spurious_summary$r.squared > dw) {
  cat("SPURIOUS!\n")
} else {
  cat("OK\n")
}

# Plot residuals from spurious regression
plot(residuals(spurious_model), type = "l", col = "darkgreen", lwd = 0.8,
     main = "Residuals from Spurious Regression", ylab = "Residuals", xlab = "Time")
abline(h = 0, col = "black", lty = 2)
grid()

# Test residuals for unit root
adf_resid <- adf.test(residuals(spurious_model))
cat(sprintf("\n    ADF test on residuals: stat = %.3f, p-value = %.3f\n", 
            adf_resid$statistic, adf_resid$p.value))
if (adf_resid$p.value < 0.05) {
  cat("    Residuals are stationary -> Valid regression\n")
} else {
  cat("    Residuals are NON-STATIONARY -> Spurious!\n")
}

# =============================================================================
# Part B: COINTEGRATION
# =============================================================================
cat("\n======================================================================\n")
cat("PART B: COINTEGRATION - A GENUINE LONG-RUN RELATIONSHIP\n")
cat("======================================================================\n")

# Load or simulate cointegrated series
beta_true  <- 0.85
alpha_true <- 15

if (USE_PYTHON_DATA) {
  cat("Loading Python-generated data (ex2_data.csv)...\n")
  cat("Results will match the textbook exactly.\n\n")
  data_ex2    <- read.csv("ex2_data.csv")
  income      <- data_ex2$income
  consumption <- data_ex2$consumption
} else {
  cat("Simulating cointegrated data in R (set.seed=456)...\n")
  cat("Note: numerical results differ from textbook due to different RNG.\n\n")
  set.seed(456)
  income_shocks    <- rnorm(n, mean = 0.5, sd = 1.0)
  income           <- 100 + cumsum(income_shocks)
  stationary_error <- numeric(n)
  for (t in 2:n) {
    stationary_error[t] <- 0.6 * stationary_error[t-1] + rnorm(1, 0, 1.5)
  }
  consumption <- alpha_true + beta_true * income + stationary_error
}

cat("\nData Generation (Permanent Income Hypothesis):\n")
cat("    income_t = income_{t-1} + 0.5 + e_t  (Random Walk with drift)\n")
cat(sprintf("    consumption_t = %.0f + %.2f*income_t + u_t  (Cointegrated)\n", 
            alpha_true, beta_true))
cat("    where u_t = 0.6*u_{t-1} + v_t is a stationary AR(1) process\n")
cat(sprintf("    TRUE cointegrating vector: (1, -%.2f)\n", beta_true))

# Plot cointegrated series
plot(income, type = "l", col = "blue", lwd = 0.8,
     main = "Cointegrated Series (Income & Consumption)", 
     ylab = "Value", xlab = "Time", ylim = range(c(income, consumption)))
lines(consumption, col = "red", lwd = 0.8)
legend("topleft", legend = c("Income", "Consumption"),
       col = c("blue", "red"), lty = 1, bty = "n")
grid()

dev.off()

# Unit root tests on levels
cat("\n--------------------------------------------------\n")
cat("STEP 1: Test for Unit Roots in Levels\n")
cat("--------------------------------------------------\n")

adf_income <- adf.test(income)
adf_cons <- adf.test(consumption)

cat(sprintf("    Income:      ADF stat = %.3f, p-value = %.3f -> I(1)\n", 
            adf_income$statistic, adf_income$p.value))
cat(sprintf("    Consumption: ADF stat = %.3f, p-value = %.3f -> I(1)\n", 
            adf_cons$statistic, adf_cons$p.value))

# Engle-Granger cointegration test
cat("\n--------------------------------------------------\n")
cat("STEP 2: Engle-Granger Cointegration Test\n")
cat("--------------------------------------------------\n")

# Step 2a: Estimate cointegrating regression
coint_reg <- lm(consumption ~ income)
coint_summary <- summary(coint_reg)

cat("\nCointegrating Regression: consumption_t = a + b*income_t + z_t\n")
cat(sprintf("    a (constant): %.4f\n", coef(coint_reg)[1]))
cat(sprintf("    b (income):   %.4f (true value = %.1f)\n", coef(coint_reg)[2], beta_true))
cat(sprintf("    R-squared:    %.4f\n", coint_summary$r.squared))

# Step 2b: Test residuals for stationarity
resid_coint <- residuals(coint_reg)

# Using urca package for proper EG critical values
eg_test <- ur.df(resid_coint, type = "none", lags = 1)

cat("\nADF Test on Cointegrating Residuals:\n")
cat(sprintf("    Test statistic: %.4f\n", eg_test@teststat[1]))
cat("    Critical values: 1%: -2.58, 5%: -1.95, 10%: -1.62 (standard)\n")

cat("\n    Note: Use Engle-Granger critical values (more stringent):\n")
cat("    For 2 variables: 1%: -3.90, 5%: -3.34, 10%: -3.04\n")

if (eg_test@teststat[1] < -3.34) {
  cat("\n    CONCLUSION: Residuals are stationary -> Series are COINTEGRATED\n")
} else {
  cat("\n    CONCLUSION: Cannot reject unit root -> No cointegration\n")
}

# =============================================================================
# Part C: ERROR CORRECTION MODEL
# =============================================================================
cat("\n======================================================================\n")
cat("PART C: ERROR CORRECTION MODEL (ECM)\n")
cat("======================================================================\n")

# Create ECM variables
dc <- diff(consumption)           # Delta c_t
dy <- diff(income)                # Delta y_t
ec_term <- resid_coint[-n]        # z_{t-1} = c_{t-1} - a - b*y_{t-1}

# Create data frame for ECM
ecm_data <- data.frame(
  dc = dc,
  dy = dy,
  ec_lag = ec_term
)

# Estimate ECM
ecm_model <- lm(dc ~ ec_lag + dy, data = ecm_data)
ecm_summary <- summary(ecm_model)

cat("\nECM Specification:\n")
cat("    Delta c_t = gamma + alpha*(c_{t-1} - b*y_{t-1}) + delta*Delta y_t + e_t\n")
cat("\nEstimation Results:\n")
cat("------------------------------------------------------------\n")
cat(sprintf("%-15s %10s %10s %10s\n", "Parameter", "Estimate", "Std.Err", "t-stat"))
cat("------------------------------------------------------------\n")
cat(sprintf("%-15s %10.4f %10.4f %10.4f\n", "Constant (g)", 
            coef(ecm_model)[1], ecm_summary$coefficients[1, 2], ecm_summary$coefficients[1, 3]))
cat(sprintf("%-15s %10.4f %10.4f %10.4f\n", "EC term (a)", 
            coef(ecm_model)[2], ecm_summary$coefficients[2, 2], ecm_summary$coefficients[2, 3]))
cat(sprintf("%-15s %10.4f %10.4f %10.4f\n", "Delta y (d)", 
            coef(ecm_model)[3], ecm_summary$coefficients[3, 2], ecm_summary$coefficients[3, 3]))
cat("------------------------------------------------------------\n")

alpha_ec <- coef(ecm_model)[2]

cat(sprintf("\n    Error Correction Coefficient (alpha): %.4f\n", alpha_ec))
cat(sprintf("    Standard Error: %.4f\n", ecm_summary$coefficients[2, 2]))
cat(sprintf("    t-statistic: %.4f\n", ecm_summary$coefficients[2, 3]))

if (alpha_ec < 0) {
  cat("\n    alpha < 0: System corrects toward equilibrium\n")
  half_life <- log(0.5) / log(1 + alpha_ec)
  cat(sprintf("    Speed of adjustment: %.1f%% of disequilibrium corrected per period\n", 
              abs(alpha_ec) * 100))
  cat(sprintf("    Half-life of adjustment: %.1f periods\n", half_life))
} else {
  cat("\n    alpha > 0: System is explosive (should not happen with cointegration)\n")
}

cat(sprintf("\n    Short-run effect of income (delta): %.4f\n", coef(ecm_model)[3]))
cat(sprintf("    Long-run effect of income (beta): %.4f\n", coef(coint_reg)[2]))

# Diagnostic plots for ECM
png("example2_ecm_R.png", width = 900, height = 700)
par(mfrow = c(2, 2), mar = c(4, 4, 3, 2))

# Equilibrium error
plot(resid_coint, type = "l", col = "blue", lwd = 0.8,
     main = "Equilibrium Error (z_t = c_t - a - b*y_t)",
     ylab = "Deviation from equilibrium", xlab = "Time")
abline(h = 0, col = "red", lty = 2, lwd = 1)
grid()

# ECM residuals
plot(residuals(ecm_model), type = "l", col = "darkgreen", lwd = 0.8,
     main = "ECM Residuals", ylab = "Residuals", xlab = "Time")
abline(h = 0, col = "red", lty = 2, lwd = 1)
grid()

# Actual vs Fitted
fitted_ecm <- fitted(ecm_model)
plot(dc, type = "l", col = "blue", lwd = 0.8,
     main = "Actual vs Fitted Values", ylab = expression(Delta*c[t]), xlab = "Time")
lines(fitted_ecm, col = "red", lty = 2, lwd = 0.8)
legend("topright", legend = c("Actual", "Fitted"), 
       col = c("blue", "red"), lty = c(1, 2), bty = "n")
grid()

# Error correction mechanism scatter
plot(ec_term, dc, pch = 19, col = rgb(0, 0, 1, 0.5),
     main = "Error Correction Mechanism",
     xlab = expression(z[t-1]), ylab = expression(Delta*c[t]))
abline(h = 0, col = "gray", lty = 2)
abline(v = 0, col = "gray", lty = 2)
# Add regression line
abline(a = coef(ecm_model)[1], b = alpha_ec, col = "red", lwd = 2)
legend("topright", legend = sprintf("alpha = %.3f", alpha_ec),
       col = "red", lwd = 2, bty = "n")
grid()

dev.off()

# =============================================================================
# Summary
# =============================================================================
cat("\n======================================================================\n")
cat("SUMMARY\n")
cat("======================================================================\n")
cat("\n1. SPURIOUS REGRESSION: Independent I(1) series can produce highly\n")
cat("   significant but meaningless regression results. Always test for\n")
cat("   unit roots and cointegration!\n\n")
cat("2. COINTEGRATION: When I(1) series share a common stochastic trend,\n")
cat("   their linear combination is stationary. This implies a genuine\n")
cat("   long-run equilibrium relationship.\n\n")
cat("3. ERROR CORRECTION MODEL: Cointegrated variables adjust toward their\n")
cat("   long-run equilibrium. The ECM captures both:\n")
cat("   - Short-run dynamics (Delta y effect)\n")
cat("   - Long-run equilibrium adjustment (error correction term)\n\n")
cat("   The speed of adjustment coefficient (alpha < 0) tells us how quickly\n")
cat("   deviations from equilibrium are corrected.\n")
cat("======================================================================\n")
