%% Example 3: GARCH Models for Volatility Modeling
% =========================================================================
% This example demonstrates:
% 1. Testing for ARCH effects (ARCH-LM test)
% 2. Estimating GARCH(1,1) model
% 3. Interpreting results and volatility persistence
% 4. Comparing symmetric vs asymmetric GARCH models
%
% Note: numerical results will differ from Python due to different RNG
% implementations. The DGP parameters and conclusions are identical.
% Required Toolboxes: Econometrics Toolbox, Statistics Toolbox
% Author: Alessia Paccagnini
% Textbook: Macroeconometrics
% =========================================================================

clear; clc; close all;

% =========================================================================
% DATA SOURCE SWITCH
% Set USE_PYTHON_DATA = true  → load ex3_data.csv (generated by Python)
%                                 results match the textbook exactly
% Set USE_PYTHON_DATA = false → simulate data in MATLAB (rng(456))
%                                 results follow same DGP but differ numerically
% =========================================================================
USE_PYTHON_DATA = true;   % <-- CHANGE THIS FLAG

n = 1000;

% True parameters
omega_true = 0.05;
alpha_true = 0.10;
beta_true  = 0.85;

if USE_PYTHON_DATA
    fprintf('Loading Python-generated data (ex3_data.csv)...\n');
    fprintf('Results will match the textbook exactly.\n\n');
    T       = readtable('ex3_data.csv');
    returns = T.returns;
    sigma2  = T.sigma2;
else
    fprintf('Simulating GARCH data in MATLAB (rng=456)...\n');
    fprintf('Note: numerical results differ from textbook due to different RNG.\n\n');
    rng(456);
    returns = zeros(n, 1);
    sigma2  = zeros(n, 1);
    sigma2(1) = omega_true / (1 - alpha_true - beta_true);
    for t = 2:n
        sigma2(t)  = omega_true + alpha_true * returns(t-1)^2 + beta_true * sigma2(t-1);
        returns(t) = sqrt(sigma2(t)) * randn(1);
    end
end

fprintf('\nTrue GARCH(1,1) parameters:\n');
fprintf('    omega: %.2f\n', omega_true);
fprintf('    alpha: %.2f\n', alpha_true);
fprintf('    beta:  %.2f\n', beta_true);
fprintf('    alpha + beta: %.2f (persistence)\n', alpha_true + beta_true);
fprintf('    Unconditional variance: %.4f\n', omega_true / (1 - alpha_true - beta_true));

%% Visualize the data
% =========================================================================
figure('Position', [100, 100, 1000, 800]);

subplot(3,1,1);
plot(returns, 'b-', 'LineWidth', 0.5);
yline(0, 'k-', 'LineWidth', 0.5);
title('Simulated Stock Returns', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Returns');
grid on;

subplot(3,1,2);
plot(returns.^2, 'r-', 'LineWidth', 0.5, 'Color', [1 0 0 0.5]);
hold on;
plot(sigma2, 'b-', 'LineWidth', 1);
title('Volatility Clustering', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Squared Returns / Variance');
legend('Squared Returns', 'True Conditional Variance');
grid on;

subplot(3,1,3);
histogram(returns, 50, 'Normalization', 'pdf', 'FaceAlpha', 0.7);
hold on;
x_range = linspace(min(returns), max(returns), 100);
plot(x_range, normpdf(x_range, mean(returns), std(returns)), 'r-', 'LineWidth', 2);
title('Distribution of Returns (Fat Tails)', 'FontSize', 12, 'FontWeight', 'bold');
xlabel('Returns');
legend('Returns', 'Normal Distribution');
grid on;

sgtitle('GARCH Data Visualization', 'FontSize', 14, 'FontWeight', 'bold');
saveas(gcf, 'example3_garch_data_matlab.png');

% Summary statistics
fprintf('\nSummary Statistics:\n');
fprintf('    Mean:     %.4f\n', mean(returns));
fprintf('    Std Dev:  %.4f\n', std(returns));
fprintf('    Skewness: %.4f\n', skewness(returns));
fprintf('    Kurtosis: %.4f (normal = 3)\n', kurtosis(returns));
fprintf('    -> Excess kurtosis indicates fat tails (leptokurtosis)\n');

%% Step 1: Test for ARCH Effects
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('STEP 1: TESTING FOR ARCH EFFECTS (ARCH-LM Test)\n');
fprintf('======================================================================\n');

fprintf('\nARCH-LM Test: H0: No ARCH effects (homoskedasticity)\n');
fprintf('             H1: ARCH effects present (heteroskedasticity)\n');
fprintf('--------------------------------------------------\n');

lags_test = [1, 5, 10];
for lag = lags_test
    [h, pval, stat] = archtest(returns, 'Lags', lag);
    sig_str = '';
    if pval < 0.01
        sig_str = '***';
    elseif pval < 0.05
        sig_str = '**';
    elseif pval < 0.10
        sig_str = '*';
    end
    fprintf('    Lags = %2d: LM stat = %8.3f, p-value = %.6f %s\n', lag, stat, pval, sig_str);
end
fprintf('--------------------------------------------------\n');
fprintf('    *** p<0.01, ** p<0.05, * p<0.10\n');
fprintf('\n    Strong evidence of ARCH effects -> GARCH modeling is appropriate\n');

%% Step 2: Estimate GARCH(1,1) Model
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('STEP 2: GARCH(1,1) ESTIMATION\n');
fprintf('======================================================================\n');

% Specify and estimate GARCH(1,1)
Mdl_garch = garch('GARCHLags', 1, 'ARCHLags', 1);
[EstMdl_garch, ~, logL_garch] = estimate(Mdl_garch, returns, 'Display', 'off');

% Extract parameters
omega_hat = EstMdl_garch.Constant;
alpha_hat = EstMdl_garch.ARCH{1};
beta_hat = EstMdl_garch.GARCH{1};
persistence = alpha_hat + beta_hat;

% Calculate information criteria
numParams_garch = 3; % omega, alpha, beta
aic_garch = -2*logL_garch + 2*numParams_garch;
bic_garch = -2*logL_garch + numParams_garch*log(n);

fprintf('\nGARCH(1,1) Estimation Results:\n');
fprintf('--------------------------------------------------\n');
disp(EstMdl_garch);

fprintf('\nParameter Interpretation:\n');
fprintf('    omega:    %.6f (intercept)\n', omega_hat);
fprintf('    alpha:    %.4f (reaction to shocks)\n', alpha_hat);
fprintf('    beta:     %.4f (volatility persistence)\n', beta_hat);
fprintf('    alpha + beta: %.4f (total persistence)\n', persistence);

fprintf('\nComparison with True Values:\n');
fprintf('    %-12s %10s %10s\n', 'Parameter', 'True', 'Estimated');
fprintf('    --------------------------------\n');
fprintf('    %-12s %10.4f %10.4f\n', 'omega', omega_true, omega_hat);
fprintf('    %-12s %10.4f %10.4f\n', 'alpha', alpha_true, alpha_hat);
fprintf('    %-12s %10.4f %10.4f\n', 'beta', beta_true, beta_hat);

% Unconditional variance and half-life
uncond_var = omega_hat / (1 - alpha_hat - beta_hat);
half_life = log(0.5) / log(persistence);

fprintf('\nImplied Quantities:\n');
fprintf('    Unconditional variance: %.4f\n', uncond_var);
fprintf('    Unconditional std dev:  %.4f\n', sqrt(uncond_var));
fprintf('    Half-life of shocks:    %.1f periods\n', half_life);
fprintf('    (Time for volatility shock to decay by 50%%)\n');

%% Step 3: Model Comparison (GARCH vs GJR-GARCH vs EGARCH)
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('STEP 3: MODEL COMPARISON (Symmetric vs Asymmetric)\n');
fprintf('======================================================================\n');

% Fit GJR-GARCH
Mdl_gjr = gjr('GARCHLags', 1, 'ARCHLags', 1, 'LeverageLags', 1);
[EstMdl_gjr, ~, logL_gjr] = estimate(Mdl_gjr, returns, 'Display', 'off');
numParams_gjr = 4;
aic_gjr = -2*logL_gjr + 2*numParams_gjr;
bic_gjr = -2*logL_gjr + numParams_gjr*log(n);

% Fit EGARCH
Mdl_egarch = egarch('GARCHLags', 1, 'ARCHLags', 1, 'LeverageLags', 1);
[EstMdl_egarch, ~, logL_egarch] = estimate(Mdl_egarch, returns, 'Display', 'off');
numParams_egarch = 4;
aic_egarch = -2*logL_egarch + 2*numParams_egarch;
bic_egarch = -2*logL_egarch + numParams_egarch*log(n);

fprintf('\nModel Comparison:\n');
fprintf('------------------------------------------------------------\n');
fprintf('%-20s %12s %12s %12s\n', 'Model', 'Log-Lik', 'AIC', 'BIC');
fprintf('------------------------------------------------------------\n');
fprintf('%-20s %12.2f %12.2f %12.2f\n', 'GARCH(1,1)', logL_garch, aic_garch, bic_garch);
fprintf('%-20s %12.2f %12.2f %12.2f\n', 'GJR-GARCH(1,1,1)', logL_gjr, aic_gjr, bic_gjr);
fprintf('%-20s %12.2f %12.2f %12.2f\n', 'EGARCH(1,1)', logL_egarch, aic_egarch, bic_egarch);
fprintf('------------------------------------------------------------\n');

% Find best model by BIC
[~, best_idx] = min([bic_garch, bic_gjr, bic_egarch]);
model_names = {'GARCH(1,1)', 'GJR-GARCH(1,1,1)', 'EGARCH(1,1)'};
fprintf('\nBest model by BIC: %s\n', model_names{best_idx});

% Check asymmetry in GJR-GARCH
gamma_gjr = EstMdl_gjr.Leverage{1};
fprintf('\nGJR-GARCH asymmetry parameter (gamma): %.4f\n', gamma_gjr);
if abs(gamma_gjr) > 0.01
    fprintf('    -> Evidence of asymmetric volatility (leverage effect)\n');
else
    fprintf('    -> No significant asymmetry (symmetric GARCH sufficient)\n');
end

%% Step 4: Diagnostic Checking
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('STEP 4: DIAGNOSTIC CHECKING\n');
fprintf('======================================================================\n');

% Get conditional variances and standardized residuals
[cond_var, ~] = infer(EstMdl_garch, returns);
std_resid = returns ./ sqrt(cond_var);

fprintf('\nStandardized Residuals Analysis:\n');
fprintf('    Mean:     %.4f (should be ~ 0)\n', mean(std_resid));
fprintf('    Std Dev:  %.4f (should be ~ 1)\n', std(std_resid));
fprintf('    Skewness: %.4f\n', skewness(std_resid));
fprintf('    Kurtosis: %.4f\n', kurtosis(std_resid));

% ARCH-LM test on standardized residuals
fprintf('\nARCH-LM Test on Standardized Residuals:\n');
fprintf('    (Should show NO remaining ARCH effects)\n');
for lag = [5, 10]
    [h, pval, stat] = archtest(std_resid, 'Lags', lag);
    if pval > 0.05
        result_str = 'No ARCH effects (pass)';
    else
        result_str = 'ARCH effects remain (fail)';
    end
    fprintf('    Lags = %2d: p-value = %.4f -> %s\n', lag, pval, result_str);
end

% Ljung-Box test on squared standardized residuals
fprintf('\nLjung-Box Test on Squared Standardized Residuals:\n');
for lag = [10, 20]
    [h, pval, stat] = lbqtest(std_resid.^2, 'Lags', lag);
    fprintf('    Lags = %2d: Q-stat = %.3f, p-value = %.4f\n', lag, stat, pval);
end

%% Visualization of results
% =========================================================================
figure('Position', [100, 100, 1000, 700]);

subplot(2,2,1);
cond_vol = sqrt(cond_var);
plot(cond_vol, 'b-', 'LineWidth', 0.8);
hold on;
plot(sqrt(sigma2), 'r--', 'LineWidth', 0.8);
title('Conditional Volatility (\sigma_t)', 'FontWeight', 'bold');
legend('Estimated', 'True');
grid on;

subplot(2,2,2);
plot(returns, 'Color', [0.5 0.5 0.5], 'LineWidth', 0.3);
hold on;
plot(2*cond_vol, 'r-', 'LineWidth', 1);
plot(-2*cond_vol, 'r-', 'LineWidth', 1);
title('Returns with 95% Volatility Bands', 'FontWeight', 'bold');
legend('Returns', '\pm 2\sigma bands');
grid on;

subplot(2,2,3);
plot(std_resid, 'b-', 'LineWidth', 0.5);
yline(0, 'k-', 'LineWidth', 0.5);
yline(2, 'r--', 'LineWidth', 0.5);
yline(-2, 'r--', 'LineWidth', 0.5);
title('Standardized Residuals', 'FontWeight', 'bold');
ylabel('z_t = \epsilon_t / \sigma_t');
grid on;

subplot(2,2,4);
qqplot(std_resid);
title('Q-Q Plot of Standardized Residuals', 'FontWeight', 'bold');

sgtitle('GARCH Model Diagnostics', 'FontSize', 14, 'FontWeight', 'bold');
saveas(gcf, 'example3_garch_results_matlab.png');

%% Summary
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('SUMMARY\n');
fprintf('======================================================================\n');
fprintf('\nGARCH(1,1) Model Results:\n');
fprintf('-------------------------\n');
fprintf('    sigma^2_t = %.4f + %.4f*e^2_{t-1} + %.4f*sigma^2_{t-1}\n', ...
    omega_hat, alpha_hat, beta_hat);
fprintf('\nKey Findings:\n');
fprintf('    - Strong ARCH effects detected (ARCH-LM test highly significant)\n');
fprintf('    - High persistence (alpha + beta = %.3f): volatility shocks are long-lasting\n', persistence);
fprintf('    - Half-life of %.1f periods for volatility to return halfway to normal\n', half_life);
fprintf('    - Model diagnostics: standardized residuals show no remaining ARCH effects\n');
fprintf('\nInterpretation:\n');
fprintf('    - alpha = %.3f: %.1f%% of yesterday''s squared shock affects today''s variance\n', ...
    alpha_hat, alpha_hat*100);
fprintf('    - beta = %.3f: %.1f%% of yesterday''s variance persists to today\n', ...
    beta_hat, beta_hat*100);
fprintf('    - When alpha + beta is close to 1, the process is nearly integrated (IGARCH)\n');
fprintf('======================================================================\n');
