%% Example 1: ARIMA Model Selection Using Box-Jenkins Methodology
% =========================================================================
% This example demonstrates the three-stage Box-Jenkins approach:
% 1. Identification: Plot data, test for stationarity, examine ACF/PACF
% 2. Estimation: Fit ARIMA model
% 3. Diagnostic Checking: Analyze residuals
%
% Note: numerical results will differ from Python due to different RNG
% implementations. The DGP parameters and conclusions are identical.
% Required Toolboxes: Econometrics Toolbox, Statistics Toolbox
% Author: Alessia Paccagnini
% Textbook: Macroeconometrics
% =========================================================================

clear; clc; close all;

% =========================================================================
% DATA SOURCE SWITCH
% Set USE_PYTHON_DATA = true  → load ex1_data.csv (generated by Python)
%                                 results match the textbook exactly
% Set USE_PYTHON_DATA = false → simulate data in MATLAB (rng(42))
%                                 results follow same DGP but differ numerically
% =========================================================================
USE_PYTHON_DATA = true   % <-- CHANGE THIS FLAG

%% Step 0: Simulated Data (ARMA(2,1) process)
% =========================================================================
n = 200;

% True parameters
phi1_true  = 0.4;
phi2_true  = -0.2;
theta1_true = 0.3;
c_true     = 0.5;

if USE_PYTHON_DATA
    fprintf('Loading Python-generated data (ex1_data.csv)...\n');
    fprintf('Results will match the textbook exactly.\n\n');
    T = readtable('ex1_data.csv');
    y = T.y;
else
    fprintf('Simulating data in MATLAB (rng=42)...\n');
    fprintf('Note: numerical results differ from textbook due to different RNG.\n\n');
    rng(42);
    eps = randn(n, 1);
    y   = zeros(n, 1);
    for t = 3:n
        y(t) = c_true + phi1_true*y(t-1) + phi2_true*y(t-2) + eps(t) + theta1_true*eps(t-1);
    end
end

% Create time vector (quarterly dates)
dates = datetime(1970, 1, 1) + calquarters(0:n-1)';

fprintf('======================================================================\n');
fprintf('EXAMPLE 1: ARIMA MODEL SELECTION - BOX-JENKINS METHODOLOGY\n');
fprintf('======================================================================\n');
fprintf('\nTrue DGP: y_t = %.1f + %.1f*y_{t-1} + %.1f*y_{t-2} + e_t + %.1f*e_{t-1}\n', ...
    c_true, phi1_true, phi2_true, theta1_true);

%% Stage 1: IDENTIFICATION
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('STAGE 1: IDENTIFICATION\n');
fprintf('======================================================================\n');

% 1.1 Visual Inspection
figure('Position', [100, 100, 900, 700]);

subplot(3,1,1);
plot(dates, y, 'b-', 'LineWidth', 0.8);
hold on;
yline(mean(y), 'r--', sprintf('Mean = %.2f', mean(y)), 'LineWidth', 1.5);
title('GDP Growth Rate (Simulated)', 'FontSize', 12, 'FontWeight', 'bold');
ylabel('Percent');
grid on;
legend('GDP Growth', 'Mean');

subplot(3,1,2);
autocorr(y, 'NumLags', 20);
title('Autocorrelation Function (ACF)');

subplot(3,1,3);
parcorr(y, 'NumLags', 20);
title('Partial Autocorrelation Function (PACF)');

sgtitle('Stage 1: Identification', 'FontSize', 14, 'FontWeight', 'bold');
saveas(gcf, 'example1_identification_matlab.png');

fprintf('\n1.1 Visual Inspection:\n');
fprintf('    - Time series plot shows fluctuations around a constant mean\n');
fprintf('    - No obvious trend detected\n');
fprintf('    - See figure for ACF/PACF plots\n');

% 1.2 Unit Root Tests
fprintf('\n1.2 Unit Root Tests:\n');

% ADF Test
[h_adf, pval_adf, stat_adf, cval_adf] = adftest(y, 'Model', 'ARD');
fprintf('\n    ADF Test (H0: unit root):\n');
fprintf('    Test Statistic: %.4f\n', stat_adf);
fprintf('    p-value: %.4f\n', pval_adf);
fprintf('    Critical Value (5%%): %.2f\n', cval_adf);
if h_adf == 1
    fprintf('    Conclusion: Reject H0 - Series is stationary\n');
else
    fprintf('    Conclusion: Fail to reject H0 - Series has unit root\n');
end

% KPSS Test
[h_kpss, pval_kpss, stat_kpss, cval_kpss] = kpsstest(y);
fprintf('\n    KPSS Test (H0: stationarity):\n');
fprintf('    Test Statistic: %.4f\n', stat_kpss);
fprintf('    p-value: %.4f\n', pval_kpss);
if h_kpss == 0
    fprintf('    Conclusion: Fail to reject H0 - Series is stationary\n');
else
    fprintf('    Conclusion: Reject H0 - Series is non-stationary\n');
end

fprintf('\n    Combined inference: Both tests suggest the series is STATIONARY (d=0)\n');

% 1.3 ACF/PACF interpretation
fprintf('\n1.3 ACF/PACF Interpretation:\n');
fprintf('    - ACF: Gradual decay suggests AR component\n');
fprintf('    - PACF: Significant spikes at lags 1 and 2, then cuts off\n');
fprintf('    - Tentative model: AR(2) or ARMA(2,1)\n');

%% Stage 2: ESTIMATION
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('STAGE 2: ESTIMATION\n');
fprintf('======================================================================\n');

% Define models to try
models = {
    [1, 0, 0], 'ARIMA(1,0,0)';
    [2, 0, 0], 'ARIMA(2,0,0)';
    [1, 0, 1], 'ARIMA(1,0,1)';
    [2, 0, 1], 'ARIMA(2,0,1)';
    [2, 0, 2], 'ARIMA(2,0,2)'
};

fprintf('\n2.1 Model Comparison (AIC/BIC):\n');
fprintf('--------------------------------------------------\n');
fprintf('%-15s %-12s %-12s\n', 'Model', 'AIC', 'BIC');
fprintf('--------------------------------------------------\n');

results = struct('order', {}, 'aic', {}, 'bic', {}, 'model', {});

for i = 1:size(models, 1)
    order = models{i, 1};
    name = models{i, 2};
    
    try
        Mdl = arima(order(1), order(2), order(3));
        [EstMdl, ~, logL] = estimate(Mdl, y, 'Display', 'off');
        
        % Calculate AIC and BIC
        numParams = order(1) + order(3) + 2; % AR + MA + constant + variance
        aic = -2*logL + 2*numParams;
        bic = -2*logL + numParams*log(n);
        
        results(end+1).order = order;
        results(end).aic = aic;
        results(end).bic = bic;
        results(end).model = EstMdl;
        results(end).name = name;
        
        fprintf('%-15s %-12.2f %-12.2f\n', name, aic, bic);
    catch
        fprintf('%-15s Failed to converge\n', name);
    end
end
fprintf('--------------------------------------------------\n');

% Select best model by BIC
[~, best_idx] = min([results.bic]);
best_model = results(best_idx);

fprintf('\nBest model by BIC: %s\n', best_model.name);

% Display estimation results
fprintf('\n2.2 Estimation Results for Best Model:\n');
fprintf('--------------------------------------------------\n');
disp(best_model.model);

%% Stage 3: DIAGNOSTIC CHECKING
% =========================================================================
fprintf('\n======================================================================\n');
fprintf('STAGE 3: DIAGNOSTIC CHECKING\n');
fprintf('======================================================================\n');

% Get residuals
[residuals, ~] = infer(best_model.model, y);

% 3.1 Residual plots
figure('Position', [100, 100, 900, 700]);

subplot(2,2,1);
plot(residuals, 'b-', 'LineWidth', 0.8);
yline(0, 'r--', 'LineWidth', 1);
title('Standardized Residuals', 'FontWeight', 'bold');
ylabel('Residuals');
grid on;

subplot(2,2,2);
histogram(residuals, 25, 'Normalization', 'pdf', 'FaceAlpha', 0.7);
hold on;
x_range = linspace(min(residuals), max(residuals), 100);
plot(x_range, normpdf(x_range, mean(residuals), std(residuals)), 'r-', 'LineWidth', 2);
title('Histogram of Residuals', 'FontWeight', 'bold');
xlabel('Residuals');

subplot(2,2,3);
autocorr(residuals, 'NumLags', 20);
title('ACF of Residuals');

subplot(2,2,4);
qqplot(residuals);
title('Q-Q Plot', 'FontWeight', 'bold');

sgtitle('Stage 3: Diagnostic Checking', 'FontSize', 14, 'FontWeight', 'bold');
saveas(gcf, 'example1_diagnostics_matlab.png');

fprintf('\n3.1 Residual Analysis:\n');
fprintf('    See figure for diagnostic plots\n');

% 3.2 Ljung-Box test
fprintf('\n3.2 Ljung-Box Test for Residual Autocorrelation:\n');
lags_to_test = [5, 10, 15, 20];
dof_adjustment = best_model.order(1) + best_model.order(3); % p + q

fprintf('    Lag     Q-stat      p-value\n');
fprintf('    ------------------------------\n');
all_pass = true;
for lag = lags_to_test
    [h, pval, stat] = lbqtest(residuals, 'Lags', lag, 'DOF', lag - dof_adjustment);
    fprintf('    %2d      %.3f       %.4f\n', lag, stat, pval);
    if pval < 0.05
        all_pass = false;
    end
end

if all_pass
    fprintf('\n    Conclusion: No significant autocorrelation in residuals (p > 0.05)\n');
    fprintf('    The model passes the diagnostic check!\n');
else
    fprintf('\n    Conclusion: Some autocorrelation remains - consider revising the model\n');
end

% 3.3 Summary statistics
fprintf('\n3.3 Residual Summary Statistics:\n');
fprintf('    Mean: %.4f (should be ≈ 0)\n', mean(residuals));
fprintf('    Std Dev: %.4f\n', std(residuals));
fprintf('    Skewness: %.4f (should be ≈ 0)\n', skewness(residuals));
fprintf('    Kurtosis: %.4f (should be ≈ 3 for normal)\n', kurtosis(residuals));

% Jarque-Bera test
[h_jb, pval_jb, stat_jb] = jbtest(residuals);
fprintf('\n    Jarque-Bera test: statistic = %.2f, p-value = %.4f\n', stat_jb, pval_jb);
if h_jb == 0
    fprintf('    Residuals appear normally distributed\n');
else
    fprintf('    Residuals deviate from normality\n');
end

fprintf('\n======================================================================\n');
fprintf('FINAL MODEL: %s\n', best_model.name);
fprintf('======================================================================\n');
